"""Seed Content — Chars, Gesetze, Events, Bundesrat (DE)

Revision ID: 002_seed
Revises: 001_content
Create Date: 2025-03-17

"""

import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "002_seed"
down_revision: Union[str, Sequence[str], None] = "001_content"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Seed alle Content-Tabellen mit DE-Daten aus TypeScript-Konstanten."""
    conn = op.get_bind()

    # --- chars ---
    op.bulk_insert(
        sa.table(
            "chars",
            sa.column("id"),
            sa.column("initials"),
            sa.column("color"),
            sa.column("mood_start"),
            sa.column("loyalty_start"),
            sa.column("ultimatum_mood_thresh"),
            sa.column("ultimatum_event_id"),
            sa.column("bonus_trigger"),
            sa.column("bonus_applies"),
            sa.column("sonderregel"),
        ),
        [
            {
                "id": "kanzler",
                "initials": "AH",
                "color": "#8a7030",
                "mood_start": 3,
                "loyalty_start": 5,
                "ultimatum_mood_thresh": 1,
                "ultimatum_event_id": "kanzler_ultimatum",
                "bonus_trigger": "mood>=3",
                "bonus_applies": "bt_bonus",
                "sonderregel": None,
            },
            {
                "id": "fm",
                "initials": "RL",
                "color": "#5888b8",
                "mood_start": 2,
                "loyalty_start": 3,
                "ultimatum_mood_thresh": 0,
                "ultimatum_event_id": "fm_ultimatum",
                "bonus_trigger": "mood>=4",
                "bonus_applies": "hh_boost",
                "sonderregel": None,
            },
            {
                "id": "wm",
                "initials": "PM",
                "color": "#5a9870",
                "mood_start": 4,
                "loyalty_start": 4,
                "ultimatum_mood_thresh": 0,
                "ultimatum_event_id": "wm_ultimatum",
                "bonus_trigger": "mood>=3",
                "bonus_applies": "wirt_bonus",
                "sonderregel": None,
            },
            {
                "id": "im",
                "initials": "KB",
                "color": "#c05848",
                "mood_start": 1,
                "loyalty_start": 2,
                "ultimatum_mood_thresh": 0,
                "ultimatum_event_id": "braun_ultimatum",
                "bonus_trigger": "mood>=4",
                "bonus_applies": "br_bonus",
                "sonderregel": None,
            },
            {
                "id": "jm",
                "initials": "SK",
                "color": "#9a8848",
                "mood_start": 4,
                "loyalty_start": 4,
                "ultimatum_mood_thresh": 1,
                "ultimatum_event_id": "kern_ultimatum",
                "bonus_trigger": "mood>=3",
                "bonus_applies": "jm_shield",
                "sonderregel": None,
            },
            {
                "id": "um",
                "initials": "JW",
                "color": "#6880b8",
                "mood_start": 3,
                "loyalty_start": 3,
                "ultimatum_mood_thresh": 1,
                "ultimatum_event_id": "wolf_ultimatum",
                "bonus_trigger": "mood>=4",
                "bonus_applies": "prog_boost",
                "sonderregel": None,
            },
        ],
    )

    # --- chars_i18n ---
    op.bulk_insert(
        sa.table(
            "chars_i18n",
            sa.column("char_id"),
            sa.column("locale"),
            sa.column("name"),
            sa.column("role"),
            sa.column("bio"),
            sa.column("bonus_desc"),
            sa.column("interests"),
            sa.column("keyword"),
        ),
        [
            {
                "char_id": "kanzler",
                "locale": "de",
                "name": "Anna Hoffmann",
                "role": "Kanzlerin",
                "bio": "Führt die Koalition mit pragmatischem Kurs. Hält die Fäden zusammen — aber erwartet Loyalität zurück.",
                "bonus_desc": "Gibt +5 BT-Stimmen für alle Gesetze",
                "interests": ["Koalitionsstabilität", "Wiederwahl"],
                "keyword": "Stabilität",
            },
            {
                "char_id": "fm",
                "locale": "de",
                "name": "Robert Lehmann",
                "role": "Finanzminister",
                "bio": "Strenger Haushälter der CDU. Widersetzt sich teuren Reformen konsequent — hat aber meistens Recht.",
                "bonus_desc": "Beschleunigt Gesetze ohne Haushaltskosten",
                "interests": ["Haushaltsdisziplin", "Schuldenbremse"],
                "keyword": "Haushalt",
            },
            {
                "char_id": "wm",
                "locale": "de",
                "name": "Petra Maier",
                "role": "Wirtschaftsministerin",
                "bio": "Pragmatisch und lösungsorientiert. Wichtige Verbündete — pflegt Kontakte zur Industrie und zu Länderchefs.",
                "bonus_desc": "+3% BT-Stimmen für Wirtschaftsgesetze",
                "interests": ["Standortpolitik", "Industrietransformation"],
                "keyword": "Standort",
            },
            {
                "char_id": "im",
                "locale": "de",
                "name": "Klaus Braun",
                "role": "Innenminister",
                "bio": "Konservativer Querdenker. Misstraut der Koalition grundsätzlich — sucht aktiv nach Gründen zu torpedieren.",
                "bonus_desc": "Stabilisiert Bundesrat-Stimmen in 3 Ländern",
                "interests": ["Innere Sicherheit", "Migrationsbegrenzung"],
                "keyword": "Sicherheit",
            },
            {
                "char_id": "jm",
                "locale": "de",
                "name": "Sara Kern",
                "role": "Justizministerin",
                "bio": "Juristin mit unbedingten Prinzipien. Blockiert verfassungswidrige Vorhaben — schützt aber auch die Koalition vor teuren Fehlern.",
                "bonus_desc": "Verhindert Verfassungsklagen gegen Gesetze",
                "interests": ["Rechtsstaat", "Grundrechte"],
                "keyword": "Rechtsstaat",
            },
            {
                "char_id": "um",
                "locale": "de",
                "name": "Jonas Wolf",
                "role": "Umweltminister",
                "bio": "Treibt Klimapolitik voran, manchmal gegen den Rest des Kabinetts. Starkes Netzwerk bei progressiven Wählern.",
                "bonus_desc": "+4% Zustimmung im progressiven Milieu",
                "interests": ["Klimaschutz", "Energiewende"],
                "keyword": "Klima",
            },
        ],
    )

    # --- gesetze ---
    op.bulk_insert(
        sa.table(
            "gesetze",
            sa.column("id"),
            sa.column("tags"),
            sa.column("bt_stimmen_ja"),
            sa.column("effekt_al"),
            sa.column("effekt_hh"),
            sa.column("effekt_gi"),
            sa.column("effekt_zf"),
            sa.column("effekt_lag"),
        ),
        [
            {
                "id": "ee",
                "tags": ["bund", "eu"],
                "bt_stimmen_ja": 48,
                "effekt_al": -0.3,
                "effekt_hh": -0.4,
                "effekt_gi": -0.5,
                "effekt_zf": 5,
                "effekt_lag": 4,
            },
            {
                "id": "wb",
                "tags": ["bund", "land", "kommune"],
                "bt_stimmen_ja": 55,
                "effekt_al": -0.5,
                "effekt_hh": -0.6,
                "effekt_gi": -1.2,
                "effekt_zf": 8,
                "effekt_lag": 6,
            },
            {
                "id": "sr",
                "tags": ["bund", "eu"],
                "bt_stimmen_ja": 51,
                "effekt_al": -0.8,
                "effekt_hh": -0.2,
                "effekt_gi": 1.5,
                "effekt_zf": 3,
                "effekt_lag": 5,
            },
            {
                "id": "bp",
                "tags": ["land", "bund"],
                "bt_stimmen_ja": 53,
                "effekt_al": -0.1,
                "effekt_hh": -0.5,
                "effekt_gi": -0.8,
                "effekt_zf": 6,
                "effekt_lag": 8,
            },
        ],
    )

    # --- gesetze_i18n ---
    op.bulk_insert(
        sa.table(
            "gesetze_i18n",
            sa.column("gesetz_id"),
            sa.column("locale"),
            sa.column("titel"),
            sa.column("kurz"),
            sa.column("desc"),
        ),
        [
            {
                "gesetz_id": "ee",
                "locale": "de",
                "titel": "Erneuerbare-Energien-Beschleunigungsgesetz",
                "kurz": "EE-BeschG",
                "desc": "Verdopplung der Ausbauziele, vereinfachte Genehmigung.",
            },
            {
                "gesetz_id": "wb",
                "locale": "de",
                "titel": "Bundeswohnungsbauoffensive",
                "kurz": "BWO",
                "desc": "400.000 neue Wohnungen p.a., Baurechtsreform.",
            },
            {
                "gesetz_id": "sr",
                "locale": "de",
                "titel": "Unternehmenssteuerreform",
                "kurz": "USR",
                "desc": "Körperschaftsteuer 15%, Gegenfinanzierung Digitalsteuer.",
            },
            {
                "gesetz_id": "bp",
                "locale": "de",
                "titel": "Nationales Bildungspaket",
                "kurz": "NBP",
                "desc": "Bundesfinanzierung Schulen via Kooperationsartikel.",
            },
        ],
    )

    # --- events (random + char + bundesrat) ---
    events_data = [
        # Random
        (
            "haushalt",
            "random",
            None,
            "Haushaltskrise",
            "Milliardenloch im Bundeshaushalt",
            '„Überraschende Steuermindereinnahmen reißen ein Loch von 14 Milliarden Euro."',
            "Das Finanzministerium hat die Schätzungen nach unten korrigiert. Finanzminister Lehmann fordert sofortige Gegenmaßnahmen.",
            "Haushaltsloch: Regierung unter Druck — Lehmann fordert Sparpaket",
        ),
        (
            "skandal",
            "random",
            None,
            "Politischer Skandal",
            "Medienberichte über Ministeriumsverschwendung",
            '„Der Spiegel berichtet über fragwürdige Beraterverträge im Bundesministerium."',
            "Die Opposition fordert Rücktritt. Braun nutzt die Gelegenheit, die Koalition zu destabilisieren.",
            "Spiegel-Bericht erschüttert Koalition — Opposition wittert Morgenluft",
        ),
        (
            "euklage",
            "random",
            None,
            "EU-Vertragsverletzung",
            "Brüssel leitet Verfahren gegen Deutschland ein",
            '„Die Europäische Kommission kritisiert die schleppende Umsetzung von EU-Richtlinien."',
            "Drei Richtlinien sind noch nicht in nationales Recht überführt. Ein Bußgeld von bis zu 500 Mio. Euro droht.",
            "EU-Vertragsverletzungsverfahren gegen Deutschland eröffnet",
        ),
        (
            "konjunktur",
            "random",
            None,
            "Wirtschaftsabschwung",
            "EZB-Zinserhöhung trifft deutsche Wirtschaft",
            '„Investitionen brechen ein, Kurzarbeit steigt — Rezessionsrisiko wächst."',
            "Maier warnt vor voreiligen Ausgabenkürzungen. Lehmann besteht auf Haushaltsdisziplin.",
            "Wirtschaftsabschwung: Rezessionsrisiko steigt auf 35%",
        ),
        (
            "koalition_krise",
            "random",
            None,
            "Koalitionskrise",
            "Koalitionspartner droht mit Austritt",
            '„Wir können dieser Politik nicht mehr zustimmen", warnt der Koalitionspartner.',
            "Streit um das Energiegesetz eskaliert. Der Juniorpartner fordert Nachverhandlungen zum Koalitionsvertrag.",
            "KOALITIONSKRISE: Juniorpartner stellt Ultimatum an Kanzleramt",
        ),
        (
            "demo",
            "random",
            None,
            "Gesellschaft",
            "Großdemonstration erschüttert Berlin",
            '„500.000 Menschen auf den Straßen — die größte Demo seit Jahren."',
            "Der Protest richtet sich gegen soziale Ungleichheit. Progressive sind mobilisiert, aber auch unzufrieden mit der Regierung.",
            "Berlin: Historische Großdemonstration für soziale Gerechtigkeit",
        ),
        (
            "eufoerder",
            "random",
            None,
            "EU-Förderung",
            "EU gibt Milliarden-Strukturfonds frei",
            '„Brüssel stellt 4,8 Milliarden Euro für deutsche Klimainvestitionen bereit."',
            "Eine seltene gute Nachricht: die EU-Gelder kommen früher als erwartet. Wie werden sie eingesetzt?",
            "EU gibt 4,8 Mrd. Euro für Deutschland frei — Regierung entscheidet Verwendung",
        ),
        # Char ultimatums
        (
            "fm_ultimatum",
            "char_ultimatum",
            "fm",
            "Kabinettskrise",
            "Lehmann stellt Haushaltsultimatum",
            '„Kein einziges Gesetz ohne vollständigen Deckungsnachweis — sonst trete ich zurück."',
            "Finanzminister Lehmann ist am Ende seiner Geduld. Zu viele teure Projekte ohne Gegenfinanzierung.",
            "KABINETTSKRISE: Finanzminister Lehmann droht mit Rücktritt",
        ),
        (
            "braun_ultimatum",
            "char_ultimatum",
            "im",
            "Koalitionskonflikt",
            "Braun sabotiert Abstimmung im Bundesrat",
            '„Ich habe den Innenministern der Länder empfohlen, gegen dieses Gesetz zu stimmen."',
            "Braun hat hinter dem Rücken der Koalition agiert und drei Länder-Innenminister beeinflusst.",
            "Innenminister Braun sabotiert Koalitionspartner im Bundesrat",
        ),
        (
            "wolf_ultimatum",
            "char_ultimatum",
            "um",
            "Klimastreit",
            "Wolf droht mit Rücktritt über Klimapolitik",
            '„Wenn das Energiegesetz weiter verwässert wird, kann ich dieses Kabinett nicht mehr vertreten."',
            "Wolf ist frustriert über die schleppende Klimapolitik.",
            "Umweltminister Wolf stellt Klimaschutz-Ultimatum an Kanzleramt",
        ),
        (
            "kern_ultimatum",
            "char_ultimatum",
            "jm",
            "Verfassungskonflikt",
            "Kern blockiert Gesetz wegen Verfassungsbedenken",
            '„Ich werde kein Gesetz unterzeichnen, das vor dem Bundesverfassungsgericht keinen Bestand hat."',
            "Kern hat das Eilgesetz zur EU-Richtlinie gestoppt. Sie hat inhaltlich recht — aber die Zeit läuft.",
            "Justizministerin stoppt Eilgesetz — Verfassungsbedenken im Kabinett",
        ),
        (
            "kanzler_ultimatum",
            "char_ultimatum",
            "kanzler",
            "Vertrauensfrage",
            "Hoffmann erwägt Vertrauensfrage",
            '„Wenn die Koalition keine gemeinsame Linie findet, werde ich die Vertrauensfrage stellen."',
            "Die interne Zerrissenheit ist öffentlich geworden. Hoffmann will ein klares Bekenntnis.",
            "Kanzlerin Hoffmann erwägt Vertrauensfrage — Koalition unter Druck",
        ),
        (
            "kohl_bundesrat_sabotage",
            "bundesrat",
            None,
            "Bundesrat-Sabotage",
            "Kohl beantragt Vermittlungsausschuss",
            '„Ohne Zugeständnisse an den Osten werde ich jeden Vermittlungsausschuss beantragen."',
            "Matthias Kohl (Ostblock) hat eigenständig einen Vermittlungsausschuss-Antrag gestellt. Das Gesetz wird um mindestens 2 Monate verzögert.",
            "Kohl beantragt Vermittlungsausschuss — Gesetz verzögert",
        ),
        (
            "wm_ultimatum",
            "char_ultimatum",
            "wm",
            "Wirtschaftsstreit",
            "Maier droht mit Rücktritt über Standortpolitik",
            '„Die Kombination aus Steuererhöhung und Regulierung treibt Unternehmen ins Ausland."',
            "Maier sieht die Wirtschaftspolitik auf dem falschen Weg.",
            "Wirtschaftsministerin Maier stellt Ultimatum zur Standortpolitik",
        ),
        # Bundesrat events
        (
            "laenderfinanzausgleich",
            "bundesrat",
            None,
            "Länderfinanzausgleich",
            "Länderfinanzausgleich-Streit eskaliert",
            '„Pragmatische Mitte und Ostblock fordern Neuverteilung der Finanzströme — sonst Blockade."',
            "Fraktion Brenner und Kohl haben sich verbündet. Sie fordern eine Überarbeitung des Länderfinanzausgleichs. Ohne Zugeständnisse droht Blockade in allen zustimmungspflichtigen Gesetzen.",
            "Länderfinanzausgleich: Brenner und Kohl fordern Neuverteilung",
        ),
        (
            "landtagswahl",
            "bundesrat",
            None,
            "Landtagswahl",
            "Landtagswahl kippt Fraktion",
            '„Überraschender Regierungswechsel — die politische Landkarte verschiebt sich."',
            "Eine Landtagswahl hat die Regierungspartei in einem Bundesland gewechselt. Die Fraktionszusammensetzung im Bundesrat ändert sich. Die betroffene Fraktion muss neu verhandeln.",
            "Landtagswahl: Regierungswechsel verändert Bundesrat-Mehrheiten",
        ),
        (
            "kohl_eskaliert",
            "bundesrat",
            None,
            "Sondersitzung",
            "Kohl eskaliert — Sondersitzung einberufen",
            '„Ohne Zugeständnisse an den Osten werde ich jeden Vermittlungsausschuss beantragen."',
            "Matthias Kohl hat einen Vermittlungsausschuss-Antrag für ein laufendes Gesetz gestellt. Das Gesetz wird um 2 Monate verzögert. Wie reagieren Sie?",
            "Kohl beantragt Vermittlungsausschuss — Gesetz verzögert",
        ),
        (
            "sprecher_wechsel",
            "bundesrat",
            None,
            "Sprecher-Wechsel",
            "Neuer Fraktionssprecher im Bundesrat",
            '„Die Fraktion hat einen neuen Sprecher gewählt — mit anderen Prioritäten."',
            "Ein Fraktionssprecher wurde abgelöst. Der neue Charakter hat andere Interessen und einen neuen Tradeoff-Pool. Die Beziehung muss neu aufgebaut werden.",
            "Sprecher-Wechsel: Fraktion mit neuem Gesicht",
        ),
        (
            "bundesrat_initiative",
            "bundesrat",
            None,
            "Bundesrat-Initiative",
            "Länder bringen eigenes Gesetz ein",
            '„Die Länder wollen nicht nur reagieren — sie wollen gestalten."',
            "Eine Fraktion hat ein eigenes Gesetz eingebracht. Sie müssen entscheiden: Zustimmung stärkt die Beziehung, Blockade kostet Sympathie und Popularität.",
            "Bundesrat-Initiative: Länder fordern Mitsprache",
        ),
        (
            "foederalismusgipfel",
            "bundesrat",
            None,
            "Föderalismusgipfel",
            "Föderalismusgipfel — alle Sprecher an einem Tisch",
            '„Historische Gelegenheit: Alle vier Fraktionssprecher gleichzeitig empfangen."',
            "Beim Föderalismusgipfel können Sie alle vier Fraktionen gleichzeitig pflegen — zu reduzierten Kosten von 8 PK pro Fraktion statt 15.",
            "Föderalismusgipfel: Alle Fraktionssprecher in Berlin",
        ),
    ]

    for eid, etype, char_id, type_label, title, quote, context, ticker in events_data:
        conn.execute(
            sa.text("""
            INSERT INTO events (id, event_type, char_id)
            VALUES (:id, :event_type, :char_id)
        """),
            {"id": eid, "event_type": etype, "char_id": char_id},
        )
        conn.execute(
            sa.text("""
            INSERT INTO events_i18n (event_id, locale, type_label, title, quote, context, ticker)
            VALUES (:event_id, 'de', :type_label, :title, :quote, :context, :ticker)
        """),
            {
                "event_id": eid,
                "type_label": type_label,
                "title": title,
                "quote": quote,
                "context": context,
                "ticker": ticker,
            },
        )

    # --- event_choices + event_choices_i18n ---
    # Format: (event_id, [(choice_key, choice_type, cost_pk, effekt_al, effekt_hh, effekt_gi, effekt_zf, char_mood, loyalty, label, desc, log_msg)])
    choices_data = [
        (
            "haushalt",
            [
                (
                    "sparpaket",
                    "primary",
                    10,
                    0,
                    0.4,
                    0,
                    -5,
                    {"fm": 1},
                    {},
                    "Sparpaket durchsetzen",
                    "Kurzfristige Sanierung, senkt Popularität",
                    "Sparpaket beschlossen. Haushalt stabilisiert, Popularität sinkt.",
                ),
                (
                    "schulden",
                    "danger",
                    0,
                    0,
                    -0.2,
                    0,
                    -2,
                    {"jm": -1},
                    {},
                    "Neue Schulden aufnehmen",
                    "Verstößt gegen Schuldenbremse — rechtliches Risiko",
                    "Schuldenbremse gedehnt. Verfassungsklage droht.",
                ),
                (
                    "steuererhoehung",
                    "safe",
                    5,
                    0,
                    0.3,
                    -0.3,
                    -3,
                    {"fm": 1, "im": -1},
                    {},
                    "Steuererhöhung ankündigen",
                    "Belastet Mitte-Milieu, stabilisiert Haushalt",
                    "Steuererhöhung angekündigt. Wirtschaftsverband protestiert.",
                ),
            ],
        ),
        (
            "skandal",
            [
                (
                    "transparenz",
                    "safe",
                    0,
                    0,
                    0,
                    0,
                    -4,
                    {"im": -1, "jm": 1},
                    {},
                    "Vollständige Transparenz",
                    "Alles offenlegen, kurzfristiger Schaden",
                    "Vollständige Offenlegung. Kurzzeitiger Schaden, langfristiges Vertrauen.",
                ),
                (
                    "ablenkung",
                    "danger",
                    15,
                    0,
                    0,
                    0,
                    -2,
                    {},
                    {},
                    "Ablenkungsoffensive",
                    "Medien mit neuem Thema überspielen",
                    "Ablenkungsmanöver gestartet. Medien skeptisch.",
                ),
                (
                    "minister_entlassen",
                    "primary",
                    5,
                    0,
                    0,
                    0,
                    -1,
                    {"im": -2},
                    {},
                    "Minister entlassen",
                    "Klares Signal, kostet Koalitionsstabilität",
                    "Minister entlassen. Koalitionspartner verärgert.",
                ),
            ],
        ),
        (
            "euklage",
            [
                (
                    "schnellumsetzung",
                    "primary",
                    20,
                    0,
                    -0.1,
                    0,
                    2,
                    {"jm": -1},
                    {},
                    "Schnellumsetzung",
                    "Eilgesetzgebung, ignoriert Bundesrat",
                    "EU-Richtlinien schnell umgesetzt. Verfassungsrechtliche Bedenken bleiben.",
                ),
                (
                    "eu_verhandlung",
                    "safe",
                    8,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "EU-Verhandlung aufnehmen",
                    "Zeitgewinn, keine sofortigen Kosten",
                    "Verhandlungen mit Brüssel aufgenommen. Ergebnis offen.",
                ),
                (
                    "bundesrat_einbeziehen",
                    "safe",
                    5,
                    0,
                    -0.3,
                    0,
                    0,
                    {"fm": -1},
                    {},
                    "Bundesrat einbeziehen",
                    "Korrekt aber langsam, Bußgeld riskant",
                    "Reguläres Verfahren gewählt. Bußgeld-Risiko bleibt.",
                ),
            ],
        ),
        (
            "konjunktur",
            [
                (
                    "konjunkturpaket",
                    "primary",
                    0,
                    -0.3,
                    -0.5,
                    0,
                    4,
                    {"wm": 1, "fm": -1},
                    {},
                    "Konjunkturpaket auflegen",
                    "Teuer, aber effektiv",
                    "Konjunkturpaket beschlossen. Haushalt belastet, Wirtschaft stabilisiert.",
                ),
                (
                    "abwarten",
                    "safe",
                    0,
                    0.5,
                    0,
                    0,
                    -3,
                    {"wm": -1},
                    {},
                    "Abwarten",
                    "Günstig, aber riskant",
                    "Abwartende Haltung. Wirtschaft verschlechtert sich weiter.",
                ),
                (
                    "strukturreformen",
                    "safe",
                    10,
                    0,
                    0,
                    0,
                    1,
                    {"wm": 1, "fm": 1},
                    {},
                    "Strukturreformen ankündigen",
                    "Langfristig richtig, kurzfristig wirkungslos",
                    "Strukturreformen angekündigt. Märkte reagieren positiv.",
                ),
            ],
        ),
        (
            "koalition_krise",
            [
                (
                    "nachverhandeln",
                    "safe",
                    15,
                    0,
                    0,
                    0,
                    -2,
                    {"fm": 1},
                    {},
                    "Nachverhandeln",
                    "Stabilitätsgewinn, Reformverlust",
                    "Koalitionsvertrag nachverhandelt. Reform verwässert.",
                ),
                (
                    "konfrontation",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -6,
                    {"im": -2},
                    {},
                    "Konfrontation riskieren",
                    "Prinzipientreu, aber destabilisierend",
                    "Koalitionskrise eskaliert. Neuwahlen im Gespräch.",
                ),
                (
                    "tauschgeschaeft",
                    "primary",
                    20,
                    0,
                    0,
                    0,
                    -1,
                    {},
                    {},
                    "Tauschgeschäft anbieten",
                    "Anderes Projekt opfern, Koalition retten",
                    "Tauschgeschäft vereinbart. Koalition vorläufig gerettet.",
                ),
            ],
        ),
        (
            "demo",
            [
                (
                    "dialog",
                    "safe",
                    5,
                    0,
                    0,
                    -0.2,
                    2,
                    {"um": 1, "jm": 1},
                    {},
                    "Dialog anbieten",
                    "Signal der Offenheit",
                    "Dialog mit Demonstranten angeboten. Progressives Milieu beruhigt.",
                ),
                (
                    "ablehnen",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -3,
                    {"im": 1, "um": -1},
                    {},
                    "Forderungen ablehnen",
                    "Klare Position, aber Polarisierung",
                    "Forderungen abgelehnt. Progressive enttäuscht.",
                ),
                (
                    "sofortprogramm",
                    "primary",
                    0,
                    0,
                    -0.2,
                    -0.5,
                    4,
                    {"um": 2},
                    {},
                    "Sofortprogramm ankündigen",
                    "Teuer, hoher Sympathiegewinn",
                    "Sofortprogramm angekündigt. Breite Zustimmung.",
                ),
            ],
        ),
        (
            "eufoerder",
            [
                (
                    "klima_infra",
                    "primary",
                    0,
                    0,
                    0.3,
                    -0.3,
                    3,
                    {"um": 2, "fm": 1},
                    {},
                    "Klimaschutz & Infrastruktur",
                    "Langfristig wirksam",
                    "EU-Fonds für Klimainvestitionen eingesetzt.",
                ),
                (
                    "wohnungsbau",
                    "safe",
                    0,
                    0,
                    0.2,
                    -0.6,
                    5,
                    {"wm": 1},
                    {},
                    "Wohnungsbau priorisieren",
                    "Populär, schnell sichtbar",
                    "EU-Gelder stärken Wohnungsbauoffensive.",
                ),
                (
                    "schuldentilgung",
                    "safe",
                    0,
                    0,
                    0.5,
                    0,
                    1,
                    {"fm": 2},
                    {},
                    "Schuldentilgung",
                    "Finanzministerium begeistert",
                    "Schulden getilgt. Haushalt verbessert, Spielraum für Reformen.",
                ),
            ],
        ),
        (
            "fm_ultimatum",
            [
                (
                    "deckungsnachweis",
                    "safe",
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    {"fm": 2},
                    {"fm": 1},
                    "Deckungsnachweis zusagen",
                    "Verwässert teure Gesetze, beruhigt Lehmann",
                    "Deckungszusage gemacht. Lehmann besänftigt, Reformen eingeschränkt.",
                ),
                (
                    "widersprechen",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -4,
                    {"fm": -1, "kanzler": -1},
                    {"fm": -2},
                    "Öffentlich widersprechen",
                    "Klarer Kurs, aber Koalitionsrisiko",
                    "Öffentlicher Streit mit Lehmann. Koalition destabilisiert.",
                ),
                (
                    "sondergespraech",
                    "primary",
                    20,
                    0,
                    0,
                    0,
                    0,
                    {"fm": 1},
                    {"fm": 0},
                    "Sondergespräch einberufen",
                    "Zeitgewinn, kostet politisches Kapital",
                    "Koalitionsgipfel im Kanzleramt. Kompromiss gefunden.",
                ),
            ],
        ),
        (
            "braun_ultimatum",
            [
                (
                    "braun_rugen",
                    "danger",
                    5,
                    0,
                    0,
                    0,
                    2,
                    {"im": -2, "kanzler": 1},
                    {"im": -2},
                    "Braun öffentlich rügen",
                    "Klares Signal, Braun wird zum Feind",
                    "Braun offiziell gerügt. Interne Spannung auf Maximum.",
                ),
                (
                    "braun_einbinden",
                    "safe",
                    15,
                    0,
                    0,
                    0,
                    0,
                    {"im": 2},
                    {"im": 1},
                    "Braun einbinden",
                    "Gibt ihm Einfluss, kostet Reform-Substanz",
                    "Braun erhält Zugeständnisse. Koalition stabilisiert, Reform verwässert.",
                ),
                (
                    "braun_entlassen",
                    "primary",
                    30,
                    0,
                    0,
                    0,
                    3,
                    {"kanzler": 1, "wm": 1, "im": -3},
                    {"im": -3},
                    "Braun entlassen",
                    "Saubere Lösung, braucht Koalitionspartner",
                    "Braun entlassen. Kabinett umgebildet.",
                ),
            ],
        ),
        (
            "wolf_ultimatum",
            [
                (
                    "energiegesetz",
                    "safe",
                    10,
                    0,
                    0,
                    0,
                    3,
                    {"um": 2, "fm": -1},
                    {"um": 1},
                    "Energiegesetz priorisieren",
                    "Wolf zufrieden, progressive Stimmen steigen",
                    "Energiegesetz auf die Prioritätsliste gesetzt. Wolf bleibt.",
                ),
                (
                    "wolf_ueberzeugen",
                    "primary",
                    15,
                    0,
                    0,
                    0,
                    0,
                    {"um": 1},
                    {"um": 0},
                    "Wolf überzeugen zu bleiben",
                    "Symbolisches Zugeständnis",
                    "Persönliches Gespräch mit Wolf. Vorläufige Einigung.",
                ),
                (
                    "ruecktritt_akzeptieren",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -8,
                    {},
                    {"um": -3},
                    "Rücktritt akzeptieren",
                    "Wolf geht, progressives Milieu bricht ein",
                    "Wolf tritt zurück. Progressive Wähler fühlen sich verraten.",
                ),
            ],
        ),
        (
            "kern_ultimatum",
            [
                (
                    "gesetz_anpassen",
                    "safe",
                    10,
                    0,
                    0,
                    0,
                    0,
                    {"jm": 2},
                    {"jm": 1},
                    "Gesetz verfassungskonform anpassen",
                    "Verzögerung, aber rechtssicher",
                    "Gesetz überarbeitet. Verfassungsrechtlich sauber, aber verzögert.",
                ),
                (
                    "expertenkommission",
                    "safe",
                    8,
                    0,
                    0,
                    0,
                    0,
                    {"jm": 1},
                    {"jm": 0},
                    "Expertenkommission einsetzen",
                    "Weiterer Zeitgewinn",
                    "Verfassungskommission eingesetzt. Kern kooperiert.",
                ),
                (
                    "druck_ausueben",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -3,
                    {"jm": -2},
                    {"jm": -2},
                    "Politischen Druck ausüben",
                    "Riskant — Kern könnte klagen",
                    "Kern fühlt sich übergangen. Verfassungsklage droht.",
                ),
            ],
        ),
        (
            "kanzler_ultimatum",
            [
                (
                    "koalitionsgipfel",
                    "primary",
                    20,
                    0,
                    0,
                    0,
                    2,
                    {"kanzler": 2, "fm": 1, "wm": 1},
                    {"kanzler": 1},
                    "Koalitionsgipfel einberufen",
                    "Alle Konflikte auf den Tisch",
                    "Koalitionsgipfel schafft neue Einigkeit.",
                ),
                (
                    "vertrauensfrage",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -5,
                    {},
                    {},
                    "Vertrauensfrage riskieren",
                    "Gamble — gewinnen oder Neuwahl",
                    "Vertrauensfrage gestellt. Koalition hält knapp.",
                ),
            ],
        ),
        (
            "kohl_bundesrat_sabotage",
            [
                (
                    "verzoegerung_akzeptieren",
                    "safe",
                    0,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Verzögerung akzeptieren",
                    "Gesetz wird 2 Monate später abgestimmt",
                    "Vermittlungsausschuss-Verfahren läuft. Abstimmung verzögert.",
                ),
                (
                    "kohl_ansprechen",
                    "primary",
                    15,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Kohl direkt ansprechen",
                    "Beziehungspflege, kostet 15 PK",
                    "Gespräch mit Kohl. Beziehung verbessert, Verzögerung bleibt.",
                ),
                (
                    "oeffentlich_kritisieren",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -2,
                    {},
                    {},
                    "Öffentlich kritisieren",
                    "Beziehung zu Kohl sinkt weiter",
                    "Kohl öffentlich kritisiert. Ostblock verhärtet Position.",
                ),
            ],
        ),
        (
            "wm_ultimatum",
            [
                (
                    "steuerreform",
                    "safe",
                    0,
                    -0.3,
                    -0.3,
                    0,
                    0,
                    {"wm": 2, "fm": -1},
                    {"wm": 1},
                    "Steuerreform beschleunigen",
                    "Maier bleibt, Haushalt leidet",
                    "Steuerreform vorgezogen. Wirtschaft stabilisiert, Haushalt belastet.",
                ),
                (
                    "regulierung_zurueck",
                    "primary",
                    0,
                    -0.4,
                    0,
                    0.5,
                    -2,
                    {"wm": 2, "um": -1},
                    {"wm": 1},
                    "Regulierung zurücknehmen",
                    "Populär bei Industrie, unpopulär bei Progressiven",
                    "Regulierungspause beschlossen. Industrie erleichtert.",
                ),
                (
                    "maier_ueberstimmen",
                    "danger",
                    10,
                    0,
                    0,
                    0,
                    0,
                    {"wm": -2},
                    {"wm": -1},
                    "Maier überstimmen",
                    "Koalitionsdisziplin, Maier verliert Einfluss",
                    "Koalitionsdisziplin erzwungen. Maier fügt sich.",
                ),
            ],
        ),
        (
            "laenderfinanzausgleich",
            [
                (
                    "zugestaendnisse",
                    "primary",
                    0,
                    0,
                    -0.2,
                    0,
                    0,
                    {},
                    {},
                    "Zugeständnisse machen",
                    "Haushalt -0.2, Beziehung Brenner +8",
                    "Zugeständnisse beim Länderfinanzausgleich. Brenner zufrieden, Haushalt belastet.",
                ),
                (
                    "ablehnen_br",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Ablehnen",
                    "Beziehung Brenner -10, Kohl -8",
                    "Forderungen abgelehnt. Brenner und Kohl verärgert.",
                ),
                (
                    "gutachten",
                    "safe",
                    15,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Gutachten beauftragen",
                    "Zeitgewinn, kostet 15 PK",
                    "Wissenschaftliches Gutachten beauftragt. Thema vorerst vertagt.",
                ),
            ],
        ),
        (
            "landtagswahl",
            [
                (
                    "mehrheiten_akzeptieren",
                    "primary",
                    0,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Neue Mehrheiten akzeptieren",
                    "Politische Realität anerkennen",
                    "Regierungswechsel akzeptiert. Fraktionszusammensetzung aktualisiert.",
                ),
            ],
        ),
        (
            "kohl_eskaliert",
            [
                (
                    "kooperieren",
                    "primary",
                    15,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Kooperieren",
                    "Beziehung Kohl verbessern, 15 PK",
                    "Kooperation mit Kohl. Beziehung verbessert, Verzögerung bleibt.",
                ),
                (
                    "juristisch_blockieren",
                    "safe",
                    20,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Juristisch blockieren",
                    "Rechtliche Schritte, kostet 20 PK",
                    "Juristische Prüfung eingeleitet. Verzögerung bleibt, Kohl verärgert.",
                ),
                (
                    "oeffentlich_kritisieren_kohl",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -2,
                    {},
                    {},
                    "Öffentlich kritisieren",
                    "Beziehung Kohl sinkt weiter",
                    "Kohl öffentlich kritisiert. Ostblock verhärtet Position.",
                ),
            ],
        ),
        (
            "sprecher_wechsel",
            [
                (
                    "sprecher_einbinden",
                    "primary",
                    0,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Neuen Sprecher einbinden",
                    "Beziehungspflege beginnen",
                    "Neuer Sprecher anerkannt. Beziehungsaufbau erforderlich.",
                ),
            ],
        ),
        (
            "bundesrat_initiative",
            [
                (
                    "zustimmen",
                    "primary",
                    0,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Zustimmen",
                    "Beziehung zur initiierenden Fraktion +12",
                    "Bundesrat-Initiative zugestimmt. Beziehung zur Fraktion verbessert.",
                ),
                (
                    "blockieren",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    -3,
                    {},
                    {},
                    "Blockieren",
                    "Beziehung -15, Popularität -3",
                    "Bundesrat-Initiative blockiert. Fraktion verärgert, Popularität sinkt.",
                ),
            ],
        ),
        (
            "foederalismusgipfel",
            [
                (
                    "alle_pflegen",
                    "primary",
                    32,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Alle vier Fraktionen pflegen",
                    "32 PK (8 pro Fraktion), Beziehung +3 bei allen",
                    "Föderalismusgipfel: Beziehung zu allen Fraktionen verbessert.",
                ),
                (
                    "mitte_ostblock",
                    "safe",
                    16,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Nur Mitte und Ostblock einladen",
                    "16 PK, Beziehung +3 bei Brenner und Kohl",
                    "Föderalismusgipfel mit Brenner und Kohl. Beziehung verbessert.",
                ),
                (
                    "gipfel_absagen",
                    "danger",
                    0,
                    0,
                    0,
                    0,
                    0,
                    {},
                    {},
                    "Gipfel absagen",
                    "Keine Kosten, verpasste Chance",
                    "Föderalismusgipfel abgesagt. Chance verpasst.",
                ),
            ],
        ),
    ]

    choice_id = 1
    for event_id, choices in choices_data:
        for c in choices:
            (ckey, ctype, cost, ea, eh, eg, ez, cm, ly, label, desc, log) = c
            cm_json = json.dumps(cm) if cm else "{}"
            ly_json = json.dumps(ly) if ly else "{}"
            conn.execute(
                sa.text("""
                INSERT INTO event_choices (id, event_id, choice_key, choice_type, cost_pk, effekt_al, effekt_hh, effekt_gi, effekt_zf, char_mood, loyalty)
                VALUES (:id, :event_id, :choice_key, :choice_type, :cost_pk, :ea, :eh, :eg, :ez, CAST(:cm AS jsonb), CAST(:ly AS jsonb))
            """),
                {
                    "id": choice_id,
                    "event_id": event_id,
                    "choice_key": ckey,
                    "choice_type": ctype,
                    "cost_pk": cost,
                    "ea": ea,
                    "eh": eh,
                    "eg": eg,
                    "ez": ez,
                    "cm": cm_json,
                    "ly": ly_json,
                },
            )
            conn.execute(
                sa.text("""
                INSERT INTO event_choices_i18n (choice_id, locale, label, "desc", log_msg)
                VALUES (:choice_id, 'de', :label, :desc, :log_msg)
            """),
                {"choice_id": choice_id, "label": label, "desc": desc, "log_msg": log},
            )
            choice_id += 1

    conn.execute(
        sa.text("SELECT setval('event_choices_id_seq', :max_id)"),
        {"max_id": choice_id - 1},
    )

    # --- bundesrat_fraktionen ---
    op.bulk_insert(
        sa.table(
            "bundesrat_fraktionen",
            sa.column("id"),
            sa.column("laender"),
            sa.column("basis_bereitschaft"),
            sa.column("beziehung_start"),
            sa.column("sonderregel"),
            sa.column("sprecher_initials"),
            sa.column("sprecher_color"),
        ),
        [
            {
                "id": "koalitionstreue",
                "laender": ["NW", "NI", "HH", "HB", "SH"],
                "basis_bereitschaft": 85,
                "beziehung_start": 65,
                "sonderregel": None,
                "sprecher_initials": "PS",
                "sprecher_color": "#e03030",
            },
            {
                "id": "pragmatische_mitte",
                "laender": ["RP", "SL", "BE", "HE"],
                "basis_bereitschaft": 55,
                "beziehung_start": 40,
                "sonderregel": None,
                "sprecher_initials": "HB",
                "sprecher_color": "#9a8848",
            },
            {
                "id": "konservativer_block",
                "laender": ["BY", "BW", "ST"],
                "basis_bereitschaft": 20,
                "beziehung_start": 15,
                "sonderregel": None,
                "sprecher_initials": "EH",
                "sprecher_color": "#2a5090",
            },
            {
                "id": "ostblock",
                "laender": ["BB", "SN", "TH", "MV"],
                "basis_bereitschaft": 30,
                "beziehung_start": 25,
                "sonderregel": "kohl_saboteur",
                "sprecher_initials": "MK",
                "sprecher_color": "#5a5a5a",
            },
        ],
    )

    # --- bundesrat_fraktionen_i18n ---
    op.bulk_insert(
        sa.table(
            "bundesrat_fraktionen_i18n",
            sa.column("fraktion_id"),
            sa.column("locale"),
            sa.column("name"),
            sa.column("sprecher_name"),
            sa.column("sprecher_partei"),
            sa.column("sprecher_land"),
            sa.column("sprecher_bio"),
        ),
        [
            {
                "fraktion_id": "koalitionstreue",
                "locale": "de",
                "name": "Koalitionstreue",
                "sprecher_name": "Petra Schulz",
                "sprecher_partei": "SPD",
                "sprecher_land": "Niedersachsen",
                "sprecher_bio": "Pragmatisch und kooperativ. Verlässliche Basis, aber empfindlich wenn Bundespolitik Länderzuständigkeiten übergeht.",
            },
            {
                "fraktion_id": "pragmatische_mitte",
                "locale": "de",
                "name": "Pragmatische Mitte",
                "sprecher_name": "Hans Brenner",
                "sprecher_partei": "SPD",
                "sprecher_land": "Rheinland-Pfalz",
                "sprecher_bio": "Der entscheidende Wechselwähler. Offen für Deals, aber verhandelt immer. Ohne Gegenleistung unberechenbar.",
            },
            {
                "fraktion_id": "konservativer_block",
                "locale": "de",
                "name": "Konservativer Block",
                "sprecher_name": "Edmund Huber",
                "sprecher_partei": "CSU",
                "sprecher_land": "Bayern",
                "sprecher_bio": "Ideologischer Gegner der Koalition. Stimmt grundsätzlich gegen Rot-Grün — Ausnahme: wenn ein Gesetz Länderrechte stärkt.",
            },
            {
                "fraktion_id": "ostblock",
                "locale": "de",
                "name": "Ostblock",
                "sprecher_name": "Matthias Kohl",
                "sprecher_partei": "CDU",
                "sprecher_land": "Sachsen",
                "sprecher_bio": "Der Unberechenbare. Strukturwandel-Trauma prägt alle Entscheidungen. Investitionen in den Osten öffnen ihn — ignoriert man ihn, wird er aktiver Saboteur.",
            },
        ],
    )

    # --- bundesrat_tradeoffs ---
    tradeoffs_data = [
        ("koalitionstreue", "koal_hafen", -0.3, 0, -0.3, 0, {"wm": 1}),
        ("koalitionstreue", "koal_bildung_veto", 0, 0, 0, -2, {}),
        ("koalitionstreue", "koal_strukturfonds", -0.4, 0, -0.3, 0, {}),
        ("pragmatische_mitte", "mitte_digitalsteuer", -0.2, 0, 0.5, 0, {}),
        ("pragmatische_mitte", "mitte_weinbau", 0, 0, -0.2, 0, {"um": -1}),
        ("pragmatische_mitte", "mitte_kommune", -0.5, 0, 0, 4, {}),
        ("konservativer_block", "kons_foederal", 0, 0, 0, -3, {}),
        ("konservativer_block", "kons_bildung", 0, 0, 0, -4, {"kanzler": -1}),
        ("konservativer_block", "kons_auto", 0, 0, -0.4, 0, {"um": -2}),
        ("ostblock", "ost_invest", -0.8, 0, -0.5, 5, {}),
        ("ostblock", "ost_kohle", 0, 0, -0.6, 0, {"um": -2}),
        ("ostblock", "ost_abschreibung", -0.3, 0, 0.3, 0, {}),
    ]

    tradeoff_i18n_data = [
        (
            "koal_hafen",
            "Hafennfrastruktur ins Konjunkturpaket",
            "Norddeutsche Häfen erhalten zusätzliche Mittel — belastet den Haushalt.",
        ),
        (
            "koal_bildung_veto",
            "Bildungspaket mit Länder-Veto-Rechten",
            "Länder erhalten erweiterte Vetorechte bei Bildungsentscheidungen.",
        ),
        (
            "koal_strukturfonds",
            "Strukturfondsmittel erhöhen",
            "Mehr EU-Strukturfondsmittel für norddeutsche Regionen.",
        ),
        (
            "mitte_digitalsteuer",
            "Keine Digitalsteuer auf Mittelstand",
            "Mittelständische Unternehmen von Digitalsteuer ausnehmen.",
        ),
        (
            "mitte_weinbau",
            "Weinbau-Ausnahmeregelung im Energiegesetz",
            "Weinbau erhält Sonderregelungen bei Energievorgaben.",
        ),
        (
            "mitte_kommune",
            "Kommunale Infrastrukturmittel verdoppeln",
            "Verdopplung der Bundesmittel für kommunale Infrastruktur.",
        ),
        (
            "kons_foederal",
            "Verfassungsrechtliche Föderalismusgarantie",
            "Föderalismus in Verfassung stärker verankern.",
        ),
        (
            "kons_bildung",
            "Keine Bundeskompetenz für Bildung",
            "Bildung bleibt ausschließlich Ländersache.",
        ),
        (
            "kons_auto",
            "Automobilindustrie-Ausnahme im EE-Gesetz",
            "Automobilindustrie erhält Übergangsfristen.",
        ),
        (
            "ost_invest",
            "Investitionsprogramm Ostdeutschland (€3 Mrd.)",
            "Sonderprogramm für ostdeutsche Strukturförderung.",
        ),
        (
            "ost_kohle",
            "Kohleausstieg um 3 Jahre verschieben",
            "Längere Übergangsfristen für ostdeutsche Kohleregionen.",
        ),
        (
            "ost_abschreibung",
            "Sonderabschreibungen für ostdeutsche Unternehmen",
            "Steuerliche Anreize für Investitionen im Osten.",
        ),
    ]

    for fid, tkey, ea, eh, eg, ez, cm in tradeoffs_data:
        cm_json = json.dumps(cm) if cm else "{}"
        conn.execute(
            sa.text("""
            INSERT INTO bundesrat_tradeoffs (fraktion_id, tradeoff_key, effekt_al, effekt_hh, effekt_gi, effekt_zf, char_mood)
            VALUES (:fid, :tkey, :ea, :eh, :eg, :ez, CAST(:cm AS jsonb))
        """),
            {
                "fid": fid,
                "tkey": tkey,
                "ea": ea,
                "eh": eh,
                "eg": eg,
                "ez": ez,
                "cm": cm_json,
            },
        )

    # Get tradeoff IDs (they're sequential 1-12)
    for i, (_tkey, label, desc) in enumerate(tradeoff_i18n_data, 1):
        conn.execute(
            sa.text("""
            INSERT INTO bundesrat_tradeoffs_i18n (tradeoff_id, locale, label, "desc")
            VALUES (:tid, 'de', :label, :desc)
        """),
            {"tid": i, "label": label, "desc": desc},
        )


def downgrade() -> None:
    """Remove all seeded content."""
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM bundesrat_tradeoffs_i18n"))
    conn.execute(sa.text("DELETE FROM bundesrat_tradeoffs"))
    conn.execute(sa.text("DELETE FROM bundesrat_fraktionen_i18n"))
    conn.execute(sa.text("DELETE FROM bundesrat_fraktionen"))
    conn.execute(sa.text("DELETE FROM event_choices_i18n"))
    conn.execute(sa.text("DELETE FROM event_choices"))
    conn.execute(sa.text("DELETE FROM events_i18n"))
    conn.execute(sa.text("DELETE FROM events"))
    conn.execute(sa.text("DELETE FROM gesetze_i18n"))
    conn.execute(sa.text("DELETE FROM gesetze"))
    conn.execute(sa.text("DELETE FROM chars_i18n"))
    conn.execute(sa.text("DELETE FROM chars"))
