"""Pool-Minister vollständige Inhalte: Bios, Interests, Eingangszitate, Keywords, Bonus-Desc (DE+EN).

Revision ID: 041_pool_minister_content
Revises: 040_consolidate_cabinet
Create Date: 2026-03-24

Aktualisiert chars_i18n für alle 31 Pool-Minister (30 aus Migration 033 + sdp_kanzler aus 040).
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "041_pool_minister_content"
down_revision: Union[str, Sequence[str], None] = "040_consolidate_cabinet"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Format: (char_id, locale, name, role, bio, eingangszitat, interests_array, keyword, bonus_desc)
CONTENT_DE: list[tuple[str, str, str, str, str, str, list[str], str, str | None]] = [
    # ── SDP ──
    (
        "sdp_fm",
        "de",
        "Robert Mayer",
        "Finanzminister",
        "Ehemaliger Gewerkschaftsökonom mit Doktortitel in Volkswirtschaft. Mayer gilt als besonnener Haushälter, der Investitionen in Infrastruktur und Bildung über rigides Sparen stellt.",
        "Ein starker Staat braucht einen soliden Haushalt — aber kein Spardiktat.",
        ["Haushaltspolitik", "Steuergerechtigkeit", "Investitionen"],
        "Haushälter",
        "Bei guter Stimmung: Haushaltsdisziplin verbessert sich leicht.",
    ),
    (
        "sdp_wm",
        "de",
        "Petra Maier",
        "Wirtschaftsministerin",
        "Aufgestiegen von der Betriebsrätin zur Ministerin. Maier verbindet Standortpolitik mit Arbeitnehmerrechten und setzt auf den ökologischen Umbau der Industrie.",
        "Wirtschaft muss den Menschen dienen — nicht umgekehrt.",
        ["Standortpolitik", "Industriepolitik", "Arbeitnehmerrechte"],
        "Industriefrau",
        "Bei guter Stimmung: Arbeitslosenquote sinkt leicht.",
    ),
    (
        "sdp_am",
        "de",
        "Maria Schulze",
        "Arbeitsministerin",
        "Frühere Sozialarbeiterin und Bundestagsabgeordnete. Schulze kämpft für höhere Mindestlöhne, bessere Tarifbindung und faire Arbeitsbedingungen in der Plattformökonomie.",
        "Arbeit muss wieder zum Leben reichen.",
        ["Mindestlohn", "Tarifbindung", "Soziale Sicherung"],
        "Sozialreformerin",
        "Bei guter Stimmung: Stärkung der Arbeitnehmermilieus.",
    ),
    (
        "sdp_gm",
        "de",
        "Thomas Neumann",
        "Gesundheitsminister",
        "Ehemaliger Chefarzt und Gesundheitspolitiker. Neumann setzt sich für eine Stärkung des öffentlichen Gesundheitswesens und bessere Pflegebedingungen ein.",
        "Gesundheit darf kein Privileg sein.",
        ["Pflege", "Krankenversicherung", "Prävention"],
        "Mediziner",
        None,
    ),
    (
        "sdp_im",
        "de",
        "Klaus Werner",
        "Innenminister",
        "Langjähriger Polizeibeamter und Sicherheitsexperte. Werner steht für einen moderaten Kurs zwischen innerer Sicherheit und Bürgerrechten.",
        "Sicherheit gibt es nur mit Vertrauen in den Staat.",
        ["Innere Sicherheit", "Integration", "Katastrophenschutz"],
        "Sicherheitsmann",
        "Bei schlechter Stimmung: Risiko der Sabotage bei Gesetzesvorhaben.",
    ),
    (
        "sdp_bm",
        "de",
        "Lisa Becker",
        "Bildungsministerin",
        "Ehemalige Lehrerin und Bildungsforscherin. Becker setzt auf Chancengleichheit, digitale Bildung und eine bessere Ausfinanzierung der Schulen.",
        "Bildung ist der Schlüssel zu einer gerechten Gesellschaft.",
        ["Chancengleichheit", "Digitale Bildung", "Ausbildung"],
        "Bildungsreformerin",
        None,
    ),
    # ── CDP ──
    (
        "cdp_kanzler",
        "de",
        "Friedrich Schwarz",
        "Kanzler-Kandidat",
        "Ministerpräsident a.D. und konservativer Parteiführer. Schwarz gilt als wirtschaftsnah, werteorientiert und erfahren in Koalitionsverhandlungen.",
        "Stabilität ist kein Stillstand — es ist die Basis für Fortschritt.",
        ["Wirtschaftspolitik", "Sicherheit", "Tradition"],
        "Konservativer",
        None,
    ),
    (
        "cdp_fm",
        "de",
        "Robert Lehmann",
        "Finanzminister",
        "Ehemaliger Investmentbanker und Haushaltsexperte. Lehmann ist bekannt für seine kompromisslose Haltung zur Schuldenbremse und sein Misstrauen gegenüber Ausgabenprogrammen.",
        "Schulden von heute sind die Steuern von morgen.",
        ["Schuldenbremse", "Haushaltsdisziplin", "Steuerreform"],
        "Sparkommissar",
        "Bei guter Stimmung: Haushaltsdisziplin verbessert sich leicht.",
    ),
    (
        "cdp_im",
        "de",
        "Klaus Braun",
        "Innenminister",
        "Hardliner im Innenressort mit Verbindungen zum Sicherheitsapparat. Braun fordert härtere Maßnahmen bei Migration und Kriminalität — nicht immer im Einklang mit dem Koalitionsvertrag.",
        "Ohne Ordnung gibt es keine Freiheit.",
        ["Innere Sicherheit", "Migration", "Polizeiarbeit"],
        "Hardliner",
        "Bei schlechter Stimmung: Sabotiert Gesetzesvorhaben durch Verzögerung.",
    ),
    (
        "cdp_wm",
        "de",
        "Heinrich Mauer",
        "Wirtschaftsminister",
        "Industrielobbyist, der den Weg in die Politik fand. Mauer setzt auf Wirtschaftswachstum durch Deregulierung und Steuererleichterungen für Unternehmen.",
        "Ein starker Standort braucht starke Unternehmen.",
        ["Wirtschaftswachstum", "Industriepolitik", "Bürokratieabbau"],
        "Wirtschaftsmann",
        "Bei guter Stimmung: Arbeitslosenquote sinkt leicht.",
    ),
    (
        "cdp_jm",
        "de",
        "Sara Kern",
        "Justizministerin",
        "Verfassungsrechtlerin und ehemalige Richterin am Bundesverfassungsgericht. Kern ist die Stimme der Rechtsstaatlichkeit im Kabinett und achtet auf Grundrechtskonformität.",
        "Das Grundgesetz ist kein Vorschlag — es ist eine Verpflichtung.",
        ["Rechtsstaat", "Grundrechte", "Verfassungsschutz"],
        "Verfassungshüterin",
        None,
    ),
    (
        "cdp_bm",
        "de",
        "Monika Brandt",
        "Bildungsministerin",
        "Ehemalige Universitätspräsidentin und Forschungspolitikerin. Brandt setzt auf Exzellenz in Forschung und Lehre sowie auf eine modernisierte duale Ausbildung.",
        "Bildung und Forschung sind die Rohstoffe unserer Zukunft.",
        ["Bildung", "Forschung", "Duale Ausbildung"],
        "Forschungsministerin",
        None,
    ),
    # ── GP (Grüne) ──
    (
        "gp_kanzlerin",
        "de",
        "Lena Fischer",
        "Kanzlerin-Kandidatin",
        "Ehemalige Umweltaktivistin und Fraktionsvorsitzende. Fischer steht für einen radikalen Kurswechsel in der Klimapolitik, verbunden mit sozialer Gerechtigkeit.",
        "Die Klimakrise wartet nicht auf Koalitionsverträge.",
        ["Klimaschutz", "Soziale Gerechtigkeit", "Nachhaltigkeit"],
        "Klimakanzlerin",
        None,
    ),
    (
        "gp_um",
        "de",
        "Jonas Wolf",
        "Umweltminister",
        "Biologe und langjähriger Greenpeace-Aktivist. Wolf drängt auf ambitionierte Klimaziele und scheut den Konflikt mit der Industrie nicht. Er verlangt die Einführung einer CO₂-Steuer.",
        "Klimaschutz ist kein Luxus — er ist Überlebensstrategie.",
        ["Klimaschutz", "Energiewende", "Naturschutz"],
        "Klimaschützer",
        "Bei guter Stimmung: Progressive Milieus unterstützen die Regierung stärker.",
    ),
    (
        "gp_wm",
        "de",
        "Anna Grün",
        "Wirtschaftsministerin",
        "Ökonomin mit Schwerpunkt Kreislaufwirtschaft. Grün will Nachhaltigkeit als Wettbewerbsvorteil etablieren und die Transformation der Industrie vorantreiben.",
        "Nachhaltiges Wirtschaften ist kein Widerspruch — es ist die Zukunft.",
        ["Nachhaltigkeit", "Kreislaufwirtschaft", "Grüne Investitionen"],
        "Transformatorin",
        "Bei guter Stimmung: Arbeitslosenquote sinkt leicht.",
    ),
    (
        "gp_fm",
        "de",
        "Michael Berg",
        "Finanzminister",
        "Volkswirt und ehemaliger Berater für nachhaltige Finanzen. Berg will den Haushalt grün umbauen und klimaschädliche Subventionen streichen.",
        "Jeder Euro im Haushalt ist eine Entscheidung für oder gegen die Zukunft.",
        ["Grüne Investitionen", "Klimafinanzierung", "Subventionsabbau"],
        "Grüner Haushälter",
        "Bei guter Stimmung: Haushaltsdisziplin verbessert sich leicht.",
    ),
    (
        "gp_jm",
        "de",
        "Sophie Weber",
        "Justizministerin",
        "Menschenrechtsanwältin und Bürgerrechtlerin. Weber kämpft für ein modernes Umweltrecht und stärkere Klagemöglichkeiten für Umweltverbände.",
        "Recht muss auch die Natur schützen — nicht nur den Profit.",
        ["Bürgerrechte", "Umweltrecht", "Gleichstellung"],
        "Bürgerrechtlerin",
        None,
    ),
    (
        "gp_im",
        "de",
        "Felix Grau",
        "Innenminister",
        "Politikwissenschaftler und Demokratieforscher. Grau setzt auf Prävention statt Repression und will den Verfassungsschutz transparenter gestalten.",
        "Demokratie schützt man durch Beteiligung, nicht durch Überwachung.",
        ["Demokratieschutz", "Versammlungsrecht", "Transparenz"],
        "Demokratieschützer",
        "Bei schlechter Stimmung: Risiko der Sabotage bei Gesetzesvorhaben.",
    ),
    # ── LDP ──
    (
        "ldp_kanzler",
        "de",
        "Christian Frei",
        "Kanzler-Kandidat",
        "Erfolgreicher Unternehmer und liberaler Vordenker. Frei steht für Eigenverantwortung, schlanken Staat und digitale Innovation.",
        "Freiheit ist die beste Sozialpolitik.",
        ["Marktwirtschaft", "Freiheit", "Digitalisierung"],
        "Liberaler",
        None,
    ),
    (
        "ldp_fm",
        "de",
        "Vera Stahl",
        "Finanzministerin",
        "Ehemalige Steuerberaterin und Wirtschaftsanwältin. Stahl fordert eine umfassende Steuerreform mit niedrigeren Sätzen und breiter Bemessungsgrundlage.",
        "Weniger Steuern, mehr Leistung — so einfach ist das.",
        ["Steuerreform", "Schuldenabbau", "Entbürokratisierung"],
        "Steuersenkerin",
        "Bei guter Stimmung: Haushaltsdisziplin verbessert sich leicht.",
    ),
    (
        "ldp_wm",
        "de",
        "Marco Digital",
        "Wirtschaftsminister",
        "Tech-Gründer und Digitalstratege. Digital will Deutschland zum führenden Digitalstandort machen und setzt auf KI, Blockchain und digitale Verwaltung.",
        "Deutschland braucht ein Update — nicht nur ein Upgrade.",
        ["Digitalisierung", "Innovation", "Start-ups"],
        "Digitalisierer",
        "Bei guter Stimmung: Arbeitslosenquote sinkt leicht.",
    ),
    (
        "ldp_jm",
        "de",
        "Laura Markt",
        "Justizministerin",
        "Verfassungsrechtlerin mit Fokus auf Wirtschaftsfreiheit. Markt setzt sich für weniger Regulierung und stärkere Eigentumsrechte ein.",
        "Der beste Schutz für Bürger ist ein Staat, der sich zurückhält.",
        ["Bürgerrechte", "Wirtschaftsrecht", "Datenschutz"],
        "Freiheitsrechtlerin",
        None,
    ),
    (
        "ldp_im",
        "de",
        "Stefan Privat",
        "Innenminister",
        "Ehemaliger Datenschutzbeauftragter und Bürgerrechtler. Privat steht für einen Sicherheitsbegriff, der individuelle Freiheitsrechte achtet.",
        "Sicherheit ohne Freiheit ist keine Sicherheit.",
        ["Datenschutz", "Freiheitsrechte", "Digitale Sicherheit"],
        "Datenschützer",
        "Bei schlechter Stimmung: Risiko der Sabotage bei Gesetzesvorhaben.",
    ),
    (
        "ldp_bm",
        "de",
        "Nina Bildung",
        "Bildungsministerin",
        "Bildungsunternehmerin und Verfechterin von Start-up-Kultur an Universitäten. Bildung will die Verbindung von Wirtschaft und Hochschule stärken.",
        "Innovation beginnt im Hörsaal — nicht im Ministerium.",
        ["Bildung", "Start-ups", "Digitale Lehre"],
        "Innovationsministerin",
        None,
    ),
    # ── LP ──
    (
        "lp_kanzlerin",
        "de",
        "Rosa Volk",
        "Kanzlerin-Kandidatin",
        "Gewerkschaftsikone und langjährige Bürgerrechtlerin. Volk steht für radikale Umverteilung, Friedenspolitik und eine Stärkung der öffentlichen Daseinsvorsorge.",
        "Wer Frieden will, muss Gerechtigkeit schaffen.",
        ["Soziale Gerechtigkeit", "Frieden", "Umverteilung"],
        "Gerechtigkeitskämpferin",
        None,
    ),
    (
        "lp_fm",
        "de",
        "Karl Voss",
        "Finanzminister",
        "Marxistischer Ökonom und ehemaliger Professor. Voss fordert eine Vermögenssteuer, höhere Spitzensteuersätze und die Abschaffung der Schuldenbremse.",
        "Vermögen ohne Verantwortung ist ein Privileg auf Kosten aller.",
        ["Umverteilung", "Vermögensteuer", "Öffentliche Investitionen"],
        "Umverteiler",
        "Bei guter Stimmung: Haushaltsdisziplin verbessert sich leicht.",
    ),
    (
        "lp_am",
        "de",
        "Gerd Arbeit",
        "Arbeitsminister",
        "Ehemaliger Betriebsrat und Gewerkschaftsfunktionär. Arbeit kämpft für die 30-Stunden-Woche, höhere Mindestlöhne und ein bedingungsloses Grundeinkommen.",
        "Arbeit muss sich lohnen — für alle, nicht nur für Aktionäre.",
        ["Arbeitnehmerrechte", "Mindestlohn", "Gewerkschaften"],
        "Arbeiterführer",
        "Bei guter Stimmung: Stärkung der Arbeitnehmermilieus.",
    ),
    (
        "lp_jm",
        "de",
        "Inge Sozial",
        "Justizministerin",
        "Sozialrechtlerin und Antidiskriminierungsexpertin. Sozial setzt sich für ein gerechteres Rechtssystem ein, das Schwächere besser schützt.",
        "Gerechtigkeit misst sich am Schutz der Schwächsten.",
        ["Soziale Gerechtigkeit", "Antidiskriminierung", "Mietrecht"],
        "Sozialrechtlerin",
        None,
    ),
    (
        "lp_wm",
        "de",
        "Werner Wohn",
        "Wirtschaftsminister",
        "Wohnungspolitiker und Kritiker der Immobilienspekulation. Wohn will den sozialen Wohnungsbau massiv ausbauen und Mietpreise deckeln.",
        "Wohnen ist ein Menschenrecht — kein Spekulationsobjekt.",
        ["Wohnungsbau", "Mietpreisbremse", "Öffentliche Infrastruktur"],
        "Wohnungsminister",
        "Bei guter Stimmung: Arbeitslosenquote sinkt leicht.",
    ),
    (
        "lp_im",
        "de",
        "Petra Frieden",
        "Innenministerin",
        "Friedensaktivistin und ehemalige UN-Beobachterin. Frieden setzt auf Deeskalation, Abrüstung der Polizei und eine humane Migrationspolitik.",
        "Frieden beginnt im Innern — bei jedem einzelnen Polizeieinsatz.",
        ["Frieden", "Abrüstung", "Humane Migrationspolitik"],
        "Friedensministerin",
        "Bei schlechter Stimmung: Risiko der Sabotage bei Gesetzesvorhaben.",
    ),
]

CONTENT_EN: list[tuple[str, str, str, str, str, str, list[str], str, str | None]] = [
    # ── SDP ──
    (
        "sdp_fm",
        "en",
        "Robert Mayer",
        "Finance Minister",
        "Former trade union economist with a doctorate in economics. Mayer is a level-headed budget manager who prioritizes infrastructure and education investment over rigid austerity.",
        "A strong state needs a sound budget — but not a dictate of austerity.",
        ["Fiscal policy", "Tax fairness", "Public investment"],
        "Budget man",
        "When in good mood: Budget discipline improves slightly.",
    ),
    (
        "sdp_wm",
        "en",
        "Petra Maier",
        "Economics Minister",
        "Rose from works council member to minister. Maier combines industrial policy with workers' rights and champions the green transformation of industry.",
        "The economy must serve the people — not the other way around.",
        ["Industrial policy", "Workers' rights", "Green transition"],
        "Industry woman",
        "When in good mood: Unemployment rate decreases slightly.",
    ),
    (
        "sdp_am",
        "en",
        "Maria Schulze",
        "Labor Minister",
        "Former social worker and member of parliament. Schulze fights for higher minimum wages, stronger collective bargaining, and fair conditions in the gig economy.",
        "Work must be enough to live on again.",
        ["Minimum wage", "Collective bargaining", "Social security"],
        "Social reformer",
        "When in good mood: Strengthens worker-oriented milieus.",
    ),
    (
        "sdp_gm",
        "en",
        "Thomas Neumann",
        "Health Minister",
        "Former chief physician and health policy expert. Neumann advocates for strengthening the public health system and better conditions for care workers.",
        "Health must not be a privilege.",
        ["Care", "Health insurance", "Prevention"],
        "Physician",
        None,
    ),
    (
        "sdp_im",
        "en",
        "Klaus Werner",
        "Interior Minister",
        "Long-serving police officer and security expert. Werner takes a moderate stance between internal security and civil liberties.",
        "There is no security without trust in the state.",
        ["Internal security", "Integration", "Disaster response"],
        "Security man",
        "When in bad mood: Risk of sabotaging legislation through delays.",
    ),
    (
        "sdp_bm",
        "en",
        "Lisa Becker",
        "Education Minister",
        "Former teacher and education researcher. Becker focuses on equal opportunities, digital education, and better school funding.",
        "Education is the key to a just society.",
        ["Equal opportunity", "Digital education", "Vocational training"],
        "Education reformer",
        None,
    ),
    # ── CDP ──
    (
        "cdp_kanzler",
        "en",
        "Friedrich Schwarz",
        "Chancellor candidate",
        "Former state premier and conservative party leader. Schwarz is business-friendly, values-oriented, and experienced in coalition negotiations.",
        "Stability is not stagnation — it is the foundation for progress.",
        ["Economic policy", "Security", "Tradition"],
        "Conservative",
        None,
    ),
    (
        "cdp_fm",
        "en",
        "Robert Lehmann",
        "Finance Minister",
        "Former investment banker and budget hawk. Lehmann is known for his uncompromising stance on the debt brake and distrust of spending programs.",
        "Today's debts are tomorrow's taxes.",
        ["Debt brake", "Fiscal discipline", "Tax reform"],
        "Austerity czar",
        "When in good mood: Budget discipline improves slightly.",
    ),
    (
        "cdp_im",
        "en",
        "Klaus Braun",
        "Interior Minister",
        "Hardliner in the interior ministry with deep ties to security agencies. Braun demands tougher measures on migration and crime — not always in line with the coalition agreement.",
        "There is no freedom without order.",
        ["Internal security", "Migration", "Policing"],
        "Hardliner",
        "When in bad mood: Sabotages legislation through bureaucratic delays.",
    ),
    (
        "cdp_wm",
        "en",
        "Heinrich Mauer",
        "Economics Minister",
        "Industry lobbyist turned politician. Mauer pushes for economic growth through deregulation and tax relief for businesses.",
        "A strong economy needs strong companies.",
        ["Economic growth", "Industrial policy", "Deregulation"],
        "Business man",
        "When in good mood: Unemployment rate decreases slightly.",
    ),
    (
        "cdp_jm",
        "en",
        "Sara Kern",
        "Justice Minister",
        "Constitutional law scholar and former Federal Constitutional Court judge. Kern is the voice of rule of law in the cabinet and watches over constitutional compliance.",
        "The constitution is not a suggestion — it is an obligation.",
        ["Rule of law", "Fundamental rights", "Constitutional protection"],
        "Constitution guardian",
        None,
    ),
    (
        "cdp_bm",
        "en",
        "Monika Brandt",
        "Education Minister",
        "Former university president and research policy expert. Brandt focuses on excellence in research and teaching and modernizing vocational training.",
        "Education and research are the raw materials of our future.",
        ["Education", "Research", "Vocational training"],
        "Research minister",
        None,
    ),
    # ── GP ──
    (
        "gp_kanzlerin",
        "en",
        "Lena Fischer",
        "Chancellor candidate",
        "Former environmental activist and parliamentary leader. Fischer advocates for a radical shift in climate policy combined with social justice.",
        "The climate crisis doesn't wait for coalition agreements.",
        ["Climate protection", "Social justice", "Sustainability"],
        "Climate chancellor",
        None,
    ),
    (
        "gp_um",
        "en",
        "Jonas Wolf",
        "Environment Minister",
        "Biologist and long-time Greenpeace activist. Wolf pushes for ambitious climate targets and doesn't shy away from conflicts with industry. He demands the introduction of a carbon tax.",
        "Climate protection is not a luxury — it is a survival strategy.",
        ["Climate protection", "Energy transition", "Conservation"],
        "Climate warrior",
        "When in good mood: Progressive milieus support the government more strongly.",
    ),
    (
        "gp_wm",
        "en",
        "Anna Grün",
        "Economics Minister",
        "Economist specializing in circular economy. Grün wants to establish sustainability as a competitive advantage and drive industrial transformation.",
        "Sustainable business is not a contradiction — it is the future.",
        ["Sustainability", "Circular economy", "Green investment"],
        "Transformer",
        "When in good mood: Unemployment rate decreases slightly.",
    ),
    (
        "gp_fm",
        "en",
        "Michael Berg",
        "Finance Minister",
        "Economist and former advisor for sustainable finance. Berg wants to make the budget green and eliminate climate-harmful subsidies.",
        "Every euro in the budget is a choice for or against the future.",
        ["Green investment", "Climate finance", "Subsidy reform"],
        "Green treasurer",
        "When in good mood: Budget discipline improves slightly.",
    ),
    (
        "gp_jm",
        "en",
        "Sophie Weber",
        "Justice Minister",
        "Human rights lawyer and civil liberties advocate. Weber fights for modern environmental law and stronger legal standing for environmental organizations.",
        "The law must also protect nature — not just profit.",
        ["Civil rights", "Environmental law", "Equality"],
        "Rights advocate",
        None,
    ),
    (
        "gp_im",
        "en",
        "Felix Grau",
        "Interior Minister",
        "Political scientist and democracy researcher. Grau focuses on prevention over repression and wants to make the domestic intelligence service more transparent.",
        "Democracy is protected through participation, not surveillance.",
        ["Democracy protection", "Freedom of assembly", "Transparency"],
        "Democracy defender",
        "When in bad mood: Risk of sabotaging legislation through delays.",
    ),
    # ── LDP ──
    (
        "ldp_kanzler",
        "en",
        "Christian Frei",
        "Chancellor candidate",
        "Successful entrepreneur and liberal thinker. Frei stands for personal responsibility, a lean state, and digital innovation.",
        "Freedom is the best social policy.",
        ["Free market", "Liberty", "Digitalization"],
        "Liberal",
        None,
    ),
    (
        "ldp_fm",
        "en",
        "Vera Stahl",
        "Finance Minister",
        "Former tax consultant and business attorney. Stahl demands comprehensive tax reform with lower rates and a broader tax base.",
        "Lower taxes, more performance — it's that simple.",
        ["Tax reform", "Debt reduction", "Deregulation"],
        "Tax cutter",
        "When in good mood: Budget discipline improves slightly.",
    ),
    (
        "ldp_wm",
        "en",
        "Marco Digital",
        "Economics Minister",
        "Tech founder and digital strategist. Digital wants to make Germany the leading digital hub with a focus on AI, blockchain, and digital government.",
        "Germany needs an update — not just an upgrade.",
        ["Digitalization", "Innovation", "Start-ups"],
        "Digitalizer",
        "When in good mood: Unemployment rate decreases slightly.",
    ),
    (
        "ldp_jm",
        "en",
        "Laura Markt",
        "Justice Minister",
        "Constitutional lawyer focused on economic freedom. Markt advocates for less regulation and stronger property rights.",
        "The best protection for citizens is a state that holds back.",
        ["Civil rights", "Commercial law", "Data protection"],
        "Liberty lawyer",
        None,
    ),
    (
        "ldp_im",
        "en",
        "Stefan Privat",
        "Interior Minister",
        "Former data protection officer and civil liberties advocate. Privat takes a security approach that respects individual freedom.",
        "Security without freedom is not security.",
        ["Data protection", "Civil liberties", "Digital security"],
        "Privacy advocate",
        "When in bad mood: Risk of sabotaging legislation through delays.",
    ),
    (
        "ldp_bm",
        "en",
        "Nina Bildung",
        "Education Minister",
        "Education entrepreneur and champion of start-up culture at universities. Bildung wants to strengthen the connection between industry and higher education.",
        "Innovation starts in the lecture hall — not the ministry.",
        ["Education", "Start-ups", "Digital learning"],
        "Innovation minister",
        None,
    ),
    # ── LP ──
    (
        "lp_kanzlerin",
        "en",
        "Rosa Volk",
        "Chancellor candidate",
        "Trade union icon and long-time civil rights activist. Volk stands for radical redistribution, peace policy, and strengthening public services.",
        "Those who want peace must create justice.",
        ["Social justice", "Peace", "Redistribution"],
        "Justice fighter",
        None,
    ),
    (
        "lp_fm",
        "en",
        "Karl Voss",
        "Finance Minister",
        "Marxist economist and former professor. Voss demands a wealth tax, higher top tax rates, and the abolition of the debt brake.",
        "Wealth without responsibility is a privilege at everyone's expense.",
        ["Redistribution", "Wealth tax", "Public investment"],
        "Redistributor",
        "When in good mood: Budget discipline improves slightly.",
    ),
    (
        "lp_am",
        "en",
        "Gerd Arbeit",
        "Labor Minister",
        "Former works council member and union official. Arbeit fights for the 30-hour work week, higher minimum wages, and universal basic income.",
        "Work must pay off — for everyone, not just shareholders.",
        ["Workers' rights", "Minimum wage", "Trade unions"],
        "Workers' leader",
        "When in good mood: Strengthens worker-oriented milieus.",
    ),
    (
        "lp_jm",
        "en",
        "Inge Sozial",
        "Justice Minister",
        "Social law expert and anti-discrimination specialist. Sozial advocates for a fairer legal system that better protects the vulnerable.",
        "Justice is measured by how we protect the weakest.",
        ["Social justice", "Anti-discrimination", "Tenancy law"],
        "Social law expert",
        None,
    ),
    (
        "lp_wm",
        "en",
        "Werner Wohn",
        "Economics Minister",
        "Housing policy activist and critic of real estate speculation. Wohn wants to massively expand social housing and cap rental prices.",
        "Housing is a human right — not a speculation object.",
        ["Social housing", "Rent control", "Public infrastructure"],
        "Housing minister",
        "When in good mood: Unemployment rate decreases slightly.",
    ),
    (
        "lp_im",
        "en",
        "Petra Frieden",
        "Interior Minister",
        "Peace activist and former UN observer. Frieden focuses on de-escalation, police demilitarization, and humane migration policy.",
        "Peace begins at home — with every single police operation.",
        ["Peace", "Disarmament", "Humane migration policy"],
        "Peace minister",
        "When in bad mood: Risk of sabotaging legislation through delays.",
    ),
]


def _interests_to_pg_array(interests: list[str]) -> str:
    """Konvertiert Python-Liste in PostgreSQL-Array-Literal."""
    escaped = [i.replace("'", "''").replace('"', '\\"') for i in interests]
    return "{" + ",".join(f'"{i}"' for i in escaped) + "}"


def upgrade() -> None:
    conn = op.get_bind()

    for row in CONTENT_DE + CONTENT_EN:
        (
            char_id,
            locale,
            name,
            role,
            bio,
            eingangszitat,
            interests,
            keyword,
            bonus_desc,
        ) = row
        interests_pg = _interests_to_pg_array(interests)

        conn.execute(
            sa.text("""
                UPDATE chars_i18n
                SET name = :name,
                    role = :role,
                    bio = :bio,
                    eingangszitat = :eingangszitat,
                    interests = :interests,
                    keyword = :keyword,
                    bonus_desc = :bonus_desc
                WHERE char_id = :char_id AND locale = :locale
            """),
            {
                "char_id": char_id,
                "locale": locale,
                "name": name,
                "role": role,
                "bio": bio,
                "eingangszitat": eingangszitat,
                "interests": interests_pg,
                "keyword": keyword,
                "bonus_desc": bonus_desc,
            },
        )


def downgrade() -> None:
    """Rollback: Platzhalter-Inhalte wiederherstellen (generische Bios)."""
    conn = op.get_bind()
    conn.execute(
        sa.text("""
            UPDATE chars_i18n
            SET bio = 'Minister/in aus dem Pool.',
                eingangszitat = NULL,
                interests = '{}',
                keyword = NULL,
                bonus_desc = NULL
            WHERE char_id IN (
                SELECT id FROM chars WHERE pool_partei IS NOT NULL
            )
        """)
    )
