"""SMA-407: Gesetze aus ehem. YAML in DB — locked_until_event, fehlende Katalog-Gesetze, Single Source of Truth.

Revision ID: 051_gesetze_yaml_ssot
Revises: 050_politikfelder_erweiterung
"""

from __future__ import annotations

import json
from typing import Any, Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "051_gesetze_yaml_ssot"
down_revision: Union[str, Sequence[str], None] = "050_politikfelder_erweiterung"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SEKTOR_BY_PF: dict[str, list[dict[str, Any]]] = {
    "landwirtschaft": [
        {"sektor": "konsum", "delta": 2, "verzoegerung_monate": 1},
        {"sektor": "gruen", "delta": 2, "verzoegerung_monate": 2},
    ],
    "umwelt_energie": [
        {"sektor": "gruen", "delta": 6, "verzoegerung_monate": 2},
        {"sektor": "industrie", "delta": -3, "verzoegerung_monate": 3},
    ],
    "innere_sicherheit": [
        {"sektor": "konsum", "delta": 2, "verzoegerung_monate": 1},
        {"sektor": "finanz", "delta": -1, "verzoegerung_monate": 2},
    ],
    "digital_infrastruktur": [
        {"sektor": "finanz", "delta": 3, "verzoegerung_monate": 1},
        {"sektor": "industrie", "delta": 2, "verzoegerung_monate": 2},
    ],
    "wirtschaft_finanzen": [
        {"sektor": "industrie", "delta": 4, "verzoegerung_monate": 1},
        {"sektor": "finanz", "delta": 3, "verzoegerung_monate": 1},
    ],
    "arbeit_soziales": [
        {"sektor": "arbeit", "delta": 5, "verzoegerung_monate": 0},
        {"sektor": "konsum", "delta": 2, "verzoegerung_monate": 2},
    ],
    "bildung_forschung": [
        {"sektor": "arbeit", "delta": 3, "verzoegerung_monate": 2},
        {"sektor": "finanz", "delta": -2, "verzoegerung_monate": 1},
    ],
    "gesundheit_pflege": [
        {"sektor": "konsum", "delta": 3, "verzoegerung_monate": 0},
        {"sektor": "arbeit", "delta": 2, "verzoegerung_monate": 1},
    ],
}


def upgrade() -> None:
    op.add_column(
        "gesetze",
        sa.Column("locked_until_event", sa.Text(), nullable=True),
    )
    op.add_column(
        "gesetze",
        sa.Column("zustimmungspflichtig", sa.Boolean(), nullable=True),
    )

    conn = op.get_bind()

    # id, tags, bt, ea, eh, eg, ez, lag, foed, iw, ig, is_, pf, pfs[], ke, kl, einn, pfl, inv, minc, locked
    gesetze_rows: list[tuple[Any, ...]] = [
        (
            "verfassungsreform",
            ["bund"],
            45,
            0.0,
            -0.2,
            -0.3,
            4.0,
            10,
            False,
            -15,
            -25,
            25,
            "innere_sicherheit",
            ["digital_infrastruktur"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "verfassungsgericht",
        ),
        (
            "katastrophenschutz",
            ["bund", "land"],
            65,
            -0.1,
            -0.4,
            0.0,
            3.0,
            6,
            True,
            -25,
            -15,
            20,
            "innere_sicherheit",
            [],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "naturkatastrophe",
        ),
        (
            "cybersicherheit",
            ["bund", "eu"],
            58,
            0.0,
            -0.3,
            0.0,
            2.0,
            5,
            False,
            15,
            25,
            45,
            "digital_infrastruktur",
            ["innere_sicherheit"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "cyberangriff",
        ),
        (
            "whistleblowerschutz",
            ["bund", "eu"],
            52,
            0.0,
            -0.1,
            -0.2,
            3.0,
            4,
            False,
            -20,
            -40,
            10,
            "digital_infrastruktur",
            ["arbeit_soziales"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "whistleblower",
        ),
        (
            "tarifbindung",
            ["bund"],
            50,
            -0.2,
            -0.1,
            -0.6,
            3.0,
            5,
            False,
            -40,
            -15,
            25,
            "arbeit_soziales",
            [],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "streikwelle",
        ),
        (
            "mietrecht",
            ["bund", "land"],
            56,
            0.0,
            -0.2,
            -0.8,
            5.0,
            5,
            True,
            -50,
            -30,
            -35,
            "arbeit_soziales",
            ["wirtschaft_finanzen"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "wohnungsnot",
        ),
        (
            "demokratiefoerderung",
            ["bund"],
            60,
            0.0,
            -0.3,
            0.0,
            4.0,
            4,
            False,
            -45,
            -50,
            -30,
            "arbeit_soziales",
            ["innere_sicherheit"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "rechtsextremismus",
        ),
        (
            "fachkraefte",
            ["bund", "eu"],
            48,
            -0.6,
            0.1,
            0.0,
            2.0,
            6,
            False,
            -25,
            -35,
            -25,
            "arbeit_soziales",
            ["bildung_forschung"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "fachkraeftemangel",
        ),
        (
            "rentenreform",
            ["bund"],
            44,
            0.0,
            -0.3,
            -0.4,
            4.0,
            10,
            False,
            -20,
            5,
            15,
            "arbeit_soziales",
            ["wirtschaft_finanzen"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            3,
            "rentendebatte",
        ),
        (
            "pandemieschutz",
            ["bund", "eu"],
            62,
            0.0,
            -0.4,
            0.0,
            3.0,
            5,
            False,
            -35,
            -25,
            35,
            "gesundheit_pflege",
            ["innere_sicherheit"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "pandemie_vorbereitung",
        ),
        (
            "agrarstruktur",
            ["bund", "eu", "land"],
            47,
            -0.2,
            -0.3,
            -0.5,
            4.0,
            5,
            True,
            -35,
            -25,
            -30,
            "landwirtschaft",
            ["umwelt_energie"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "tierwohl_label",
            ["bund", "eu"],
            54,
            0.0,
            -0.1,
            -0.2,
            3.0,
            4,
            False,
            -30,
            -45,
            15,
            "landwirtschaft",
            ["umwelt_energie"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "bauernentlastung",
            ["bund", "land"],
            64,
            -0.1,
            -0.4,
            0.0,
            5.0,
            3,
            True,
            -25,
            -20,
            10,
            "landwirtschaft",
            ["wirtschaft_finanzen"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "bauernproteste",
        ),
        (
            "buergerversicherung",
            ["bund"],
            43,
            0.0,
            0.3,
            -0.8,
            4.0,
            5,
            False,
            -45,
            -30,
            -40,
            "gesundheit_pflege",
            ["arbeit_soziales"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            3,
            None,
        ),
        (
            "pflegepersonal",
            ["bund", "land"],
            63,
            0.0,
            -0.6,
            -0.3,
            7.0,
            4,
            True,
            -40,
            -25,
            -35,
            "gesundheit_pflege",
            ["arbeit_soziales"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            "pflegenotstand",
        ),
        (
            "breitband",
            ["bund", "land", "kommunen"],
            60,
            -0.3,
            -0.4,
            0.0,
            5.0,
            5,
            True,
            -25,
            -15,
            15,
            "digital_infrastruktur",
            ["arbeit_soziales"],
            0.0,
            0.0,
            0.0,
            0.0,
            True,
            2,
            None,
        ),
        (
            "verwaltungsdigital",
            ["bund", "land", "kommunen"],
            56,
            0.0,
            -0.2,
            -0.1,
            4.0,
            6,
            True,
            -15,
            -10,
            25,
            "digital_infrastruktur",
            ["innere_sicherheit"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "ki_regulierung",
            ["bund", "eu"],
            57,
            0.0,
            -0.2,
            -0.2,
            3.0,
            4,
            False,
            5,
            -25,
            20,
            "digital_infrastruktur",
            ["wirtschaft_finanzen"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            3,
            "ki_vorfall",
        ),
        (
            "deutschlandticket",
            ["bund", "land", "kommunen"],
            61,
            -0.2,
            -0.3,
            -0.6,
            7.0,
            3,
            True,
            -30,
            -25,
            10,
            "digital_infrastruktur",
            ["arbeit_soziales", "umwelt_energie"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "schienen",
            ["bund", "land"],
            62,
            -0.5,
            -0.7,
            0.0,
            6.0,
            7,
            True,
            -20,
            -30,
            15,
            "digital_infrastruktur",
            ["umwelt_energie"],
            0.0,
            0.0,
            0.0,
            0.0,
            True,
            2,
            "infrastruktur_kollaps",
        ),
        (
            "hochschulreform",
            ["bund", "land", "eu"],
            53,
            -0.2,
            -0.4,
            0.0,
            4.0,
            6,
            True,
            -25,
            -35,
            -45,
            "bildung_forschung",
            ["wirtschaft_finanzen"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "bafoegreform",
            ["bund", "land"],
            56,
            0.0,
            -0.3,
            -0.5,
            5.0,
            4,
            True,
            -35,
            -30,
            -40,
            "bildung_forschung",
            ["arbeit_soziales"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "weiterbildung",
            ["bund", "land"],
            53,
            -0.3,
            -0.3,
            -0.3,
            4.0,
            5,
            True,
            -30,
            -25,
            -30,
            "arbeit_soziales",
            ["bildung_forschung"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
        (
            "antikorruption",
            ["bund", "eu"],
            59,
            0.0,
            -0.1,
            -0.3,
            4.0,
            4,
            False,
            -15,
            -20,
            35,
            "innere_sicherheit",
            ["digital_infrastruktur"],
            0.0,
            0.0,
            0.0,
            0.0,
            False,
            2,
            None,
        ),
    ]

    for row in gesetze_rows:
        (
            gid,
            tags,
            bt,
            ea,
            eh,
            eg,
            ez,
            lag,
            foed,
            iw,
            ig,
            is_,
            pf,
            pfs,
            ke,
            kl,
            einn,
            pfl,
            inv,
            minc,
            locked,
        ) = row
        tags_sql = "{" + ",".join(f'"{t}"' for t in tags) + "}"
        sec_sql = "{" + ",".join(f'"{s}"' for s in pfs) + "}"
        sektor_json = json.dumps(SEKTOR_BY_PF.get(pf, []))
        conn.execute(
            sa.text("""
                INSERT INTO gesetze (
                    id, tags, bt_stimmen_ja, effekt_al, effekt_hh, effekt_gi, effekt_zf, effekt_lag,
                    foederalismus_freundlich, ideologie_wirtschaft, ideologie_gesellschaft, ideologie_staat,
                    politikfeld_id, politikfeld_sekundaer, kosten_einmalig, kosten_laufend, einnahmeeffekt,
                    pflichtausgaben_delta, investiv, min_complexity, sektor_effekte, locked_until_event
                )
                VALUES (
                    :id, CAST(:tags AS text[]), :bt, :ea, :eh, :eg, :ez, :lag, :foed, :iw, :ig, :is_, :pf,
                    CAST(:pfs AS text[]), :ke, :kl, :einn, :pfl, :inv, :minc, CAST(:sektor AS jsonb), :locked
                )
            """),
            {
                "id": gid,
                "tags": tags_sql,
                "bt": bt,
                "ea": ea,
                "eh": eh,
                "eg": eg,
                "ez": ez,
                "lag": lag,
                "foed": foed,
                "iw": iw,
                "ig": ig,
                "is_": is_,
                "pf": pf,
                "pfs": sec_sql,
                "ke": ke,
                "kl": kl,
                "einn": einn,
                "pfl": pfl,
                "inv": inv,
                "minc": minc,
                "sektor": sektor_json,
                "locked": locked,
            },
        )

    new_ids = [r[0] for r in gesetze_rows]
    for nid in new_ids:
        conn.execute(
            sa.text("""
                UPDATE gesetze SET ideologie_wert = GREATEST(-100, LEAST(100,
                    ROUND((COALESCE(ideologie_wirtschaft,0) + COALESCE(ideologie_gesellschaft,0)
                         + COALESCE(ideologie_staat,0)) / 3.0)::integer
                ))
                WHERE id = :id
            """),
            {"id": nid},
        )

    i18n_de = [
        (
            "verfassungsreform",
            "Grundgesetzmodernisierung",
            "GGMod",
            "Reform grundrechtlicher Schutzstandards und Digitalisierung der Verwaltung.",
        ),
        (
            "katastrophenschutz",
            "Katastrophenschutz-Modernisierung",
            "KatSchG",
            "Bundesweite Koordination, Warnsysteme, Notfallreserven.",
        ),
        (
            "cybersicherheit",
            "Cybersicherheitsstärkungsgesetz",
            "CySiG",
            "Pflicht-Sicherheitsstandards für Behörden und kritische Infrastruktur.",
        ),
        (
            "whistleblowerschutz",
            "Hinweisgeberschutzgesetz",
            "HinSchG",
            "Schutz für Whistleblower in Behörden und Unternehmen.",
        ),
        (
            "tarifbindung",
            "Tarifbindungsstärkungsgesetz",
            "TarifG",
            "Allgemeinverbindlicherklärung erleichtern, Tarifverträge stärken.",
        ),
        (
            "mietrecht",
            "Mietrechtsreform",
            "MietR",
            "Verschärfung der Mietpreisbremse, Kündigungsschutz ausweiten.",
        ),
        (
            "demokratiefoerderung",
            "Demokratiefördergesetz",
            "DemFG",
            "Dauerhafte Finanzierung von Demokratieprojekten und Extremismusprävention.",
        ),
        (
            "fachkraefte",
            "Fachkräfteeinwanderungsgesetz",
            "FEG",
            "Punktebasiertes System, beschleunigte Visa, Berufsanerkennung.",
        ),
        (
            "rentenreform",
            "Generationengerechte Rentenreform",
            "RenRef",
            "Nachhaltiges Rentensystem: Beitragsdeckel, Kapitalkomponente, Demografiefaktor.",
        ),
        (
            "pandemieschutz",
            "Pandemieschutzgesetz",
            "PanSchG",
            "Bundesweite Pandemie-Vorsorge: Impfstoffreserven, Krisenprotokolle.",
        ),
        (
            "agrarstruktur",
            "Agrarstrukturgesetz",
            "AgrStrG",
            "Reform der GAP-Subventionen: Umschichtung zu Ökoregelungen, Kleinbauern-Bonus, Tierwohl-Prämien.",
        ),
        (
            "tierwohl_label",
            "Tierwohl-Kennzeichnungsgesetz",
            "TierKG",
            "Verbindliche 4-stufige Haltungskennzeichnung auf allen Fleischprodukten im Handel.",
        ),
        (
            "bauernentlastung",
            "Bäuerliches Betriebshilfeprogramm",
            "BauerHP",
            "Sofortprogramm nach Bauernprotesten: Agrardiesel-Kompensation, Bürokratieabbau für Familienbetriebe.",
        ),
        (
            "buergerversicherung",
            "Bürgerversicherungsgesetz",
            "BuerVersG",
            "Schrittweise Einbeziehung von Beamten und Selbstständigen in die GKV, Einkommensdeckel aufheben.",
        ),
        (
            "pflegepersonal",
            "Pflegepersonalstärkungsgesetz",
            "PflegStaerkG",
            "Gesetzliche Mindestbesetzung in Pflegeeinrichtungen, Pflegegehalt-Tarifbindung, Sofortprogramm Ausbildung.",
        ),
        (
            "breitband",
            "Breitbandausbaugesetz",
            "BrBandG",
            "Recht auf schnelles Internet: FTTH-Glasfaser für alle Haushalte bis 2030, Sonderförderung ländlicher Räume.",
        ),
        (
            "verwaltungsdigital",
            "Registermodernisierungsgesetz",
            "RegModG",
            "Digitales Einwohnerregister, behördenübergreifende Datenteilung, Once-Only-Prinzip für Bürger.",
        ),
        (
            "ki_regulierung",
            "KI-Governance-Gesetz",
            "KIGovG",
            "Transparenz- und Risikopflichten für KI-Systeme in Behörden und kritischer Infrastruktur. Ergänzung zum EU AI Act.",
        ),
        (
            "deutschlandticket",
            "Deutschlandticket-Verstetigung",
            "DTktG",
            "49-€-Ticket dauerhaft bundesfinanziert, Ausweitung auf Regionalbahnen und Fahrradmitnahme.",
        ),
        (
            "schienen",
            "Schienennetz-Modernisierungsgesetz",
            "SchienenModG",
            "50 Mrd. Sonderprogramm: Digitale Stellwerke, Brückensanierung, Streckenkapazitätsausbau.",
        ),
        (
            "hochschulreform",
            "Hochschulexzellenzinitiative II",
            "HochExG",
            "Neue Förderrunde: internationale Berufungen, Exzellenzcluster, Open-Access-Pflicht für Forschungsergebnisse.",
        ),
        (
            "bafoegreform",
            "BAföG-Modernisierungsgesetz",
            "BAfoegRefG",
            "Erhöhung der Bedarfssätze um 20%, Elternunabhängigkeit ab 23, Digitalisierung des Antragsverfahrens.",
        ),
        (
            "weiterbildung",
            "Nationales Weiterbildungsgesetz",
            "NatWeiterG",
            "Rechtsanspruch auf 5 Bildungstage pro Jahr, Qualifizierungsgeld, KI-Kompetenzoffensive für Beschäftigte.",
        ),
        (
            "antikorruption",
            "Antikorruptionsgesetz",
            "AntiKorrG",
            "Verschärfte Straftatbestände, verpflichtende Compliance-Programme für Bundesbehörden, verstärkter Hinweisgeberschutz.",
        ),
    ]

    i18n_en = [
        (
            "verfassungsreform",
            "Basic Law Modernisation Act",
            "BLMod",
            "Reform of fundamental rights safeguards and digitalisation of public administration.",
        ),
        (
            "katastrophenschutz",
            "Civil Protection Modernisation Act",
            "CivProt",
            "Nationwide coordination, warning systems, emergency reserves.",
        ),
        (
            "cybersicherheit",
            "Cybersecurity Strengthening Act",
            "CySec",
            "Mandatory security standards for authorities and critical infrastructure.",
        ),
        (
            "whistleblowerschutz",
            "Whistleblower Protection Act",
            "WhProt",
            "Protection for whistleblowers in public bodies and companies.",
        ),
        (
            "tarifbindung",
            "Collective Bargaining Strengthening Act",
            "CollBarg",
            "Easier declaration of general applicability; stronger collective agreements.",
        ),
        (
            "mietrecht",
            "Tenancy Law Reform",
            "TenRef",
            "Tighter rent caps, extended protection against termination.",
        ),
        (
            "demokratiefoerderung",
            "Democracy Promotion Act",
            "DemProm",
            "Sustainable funding for democracy projects and extremism prevention.",
        ),
        (
            "fachkraefte",
            "Skilled Immigration Act",
            "SkImm",
            "Points-based system, faster visas, recognition of foreign qualifications.",
        ),
        (
            "rentenreform",
            "Intergenerational Pension Reform",
            "PensRef",
            "Sustainable pensions: contribution cap, capital component, demographic factor.",
        ),
        (
            "pandemieschutz",
            "Pandemic Preparedness Act",
            "PanProt",
            "National pandemic preparedness: vaccine reserves, crisis protocols.",
        ),
        (
            "agrarstruktur",
            "Agricultural Structure Act",
            "AgrStr",
            "CAP subsidy reform: shift to eco-rules, small-farm bonus, animal-welfare premiums.",
        ),
        (
            "tierwohl_label",
            "Animal Welfare Labelling Act",
            "AnWlLab",
            "Mandatory four-tier husbandry labelling on all meat products at retail.",
        ),
        (
            "bauernentlastung",
            "Farm Relief Programme Act",
            "FarmRel",
            "Emergency package after farmer protests: agricultural diesel compensation, less red tape for family farms.",
        ),
        (
            "buergerversicherung",
            "Citizens' Insurance Act",
            "CitIns",
            "Gradual inclusion of civil servants and self-employed in statutory health insurance; lift income caps.",
        ),
        (
            "pflegepersonal",
            "Nursing Staff Strengthening Act",
            "NursStf",
            "Legal minimum staffing in care facilities, binding pay scales, training boost.",
        ),
        (
            "breitband",
            "Broadband Expansion Act",
            "BrBand",
            "Right to fast internet: fibre to every household by 2030, extra support for rural areas.",
        ),
        (
            "verwaltungsdigital",
            "Register Modernisation Act",
            "RegMod",
            "Digital population register, cross-agency data sharing, once-only principle for citizens.",
        ),
        (
            "ki_regulierung",
            "AI Governance Act",
            "AIGov",
            "Transparency and risk duties for AI in government and critical infrastructure; complements the EU AI Act.",
        ),
        (
            "deutschlandticket",
            "Germany Ticket Permanence Act",
            "DTkt",
            "Permanent federal funding for the €49 ticket, expanded regional rail and bike take-along.",
        ),
        (
            "schienen",
            "Rail Network Modernisation Act",
            "RailMod",
            "€50 bn special programme: digital signalling, bridge repairs, extra line capacity.",
        ),
        (
            "hochschulreform",
            "University Excellence Initiative II",
            "UniEx2",
            "New funding round: international hires, excellence clusters, open-access mandate for research outputs.",
        ),
        (
            "bafoegreform",
            "Federal Student Aid Modernisation Act",
            "BAföGRef",
            "Raise needs rates by 20%, independence from parents from age 23, digital applications.",
        ),
        (
            "weiterbildung",
            "National Continuing Education Act",
            "NatCEd",
            "Legal entitlement to five training days per year, training allowance, AI skills drive for workers.",
        ),
        (
            "antikorruption",
            "Anti-Corruption Act",
            "AntiCor",
            "Tighter offences, mandatory compliance for federal agencies, stronger whistleblower protection.",
        ),
    ]

    for gesetz_id, titel, kurz, desc in i18n_de:
        conn.execute(
            sa.text("""
                INSERT INTO gesetze_i18n (gesetz_id, locale, titel, kurz, "desc")
                VALUES (:gid, 'de', :titel, :kurz, :desc)
            """),
            {"gid": gesetz_id, "titel": titel, "kurz": kurz, "desc": desc},
        )
    for gesetz_id, titel, kurz, desc in i18n_en:
        conn.execute(
            sa.text("""
                INSERT INTO gesetze_i18n (gesetz_id, locale, titel, kurz, "desc")
                VALUES (:gid, 'en', :titel, :kurz, :desc)
            """),
            {"gid": gesetz_id, "titel": titel, "kurz": kurz, "desc": desc},
        )


def downgrade() -> None:
    conn = op.get_bind()
    new_ids = [
        "verfassungsreform",
        "katastrophenschutz",
        "cybersicherheit",
        "whistleblowerschutz",
        "tarifbindung",
        "mietrecht",
        "demokratiefoerderung",
        "fachkraefte",
        "rentenreform",
        "pandemieschutz",
        "agrarstruktur",
        "tierwohl_label",
        "bauernentlastung",
        "buergerversicherung",
        "pflegepersonal",
        "breitband",
        "verwaltungsdigital",
        "ki_regulierung",
        "deutschlandticket",
        "schienen",
        "hochschulreform",
        "bafoegreform",
        "weiterbildung",
        "antikorruption",
    ]
    conn.execute(
        sa.text("""
            DELETE FROM gesetz_relationen
            WHERE gesetz_a_id = ANY(:ids) OR gesetz_b_id = ANY(:ids)
        """),
        {"ids": new_ids},
    )
    for gid in new_ids:
        conn.execute(
            sa.text("DELETE FROM gesetze_i18n WHERE gesetz_id = :g"), {"g": gid}
        )
        conn.execute(sa.text("DELETE FROM gesetze WHERE id = :g"), {"g": gid})

    op.drop_column("gesetze", "zustimmungspflichtig")
    op.drop_column("gesetze", "locked_until_event")
