"""Fehlende Zufalls-Events aus random.yaml in die DB übernehmen.

22 der 37 Events aus `backend/app/content/events/random.yaml` wurden nie in die
`events`-Tabelle geseedet (Migration 064 nahm fälschlich an, es fehlten nur 7 —
ihre UPDATEs liefen für alle 22 ins Leere). Folgen im echten, DB-gestützten Spiel:

- Alle 14 Gesetze mit `locked_until_event` (Migration 051) waren unerreichbar:
  Ihre Freischalt-Events existierten nicht, und keine Event-Option in der DB
  trug `unlocks_laws`.
- Der Zufalls-Pool bestand aus nur 7 Events.
- Die fünf Follow-up-Ketten aus dem YAML liefen ins Leere.

Diese Migration seedet die 22 Events samt Optionen (de aus dem YAML, en aus
`frontend/public/locales/en/game.json`) mit den in #273/064 kuratierten Werten für
`min_complexity`/`repeatable`/`cooldown_months`. Vier gesperrte Gesetze hatten auch im
YAML keine freischaltende Option (bauernentlastung, ki_regulierung, pflegepersonal,
schienen) — sie bekommen sie hier nach dem Muster der übrigen Events: die aktive bzw.
konstruktive Reaktion schaltet frei, die abwartende oder konfrontative nicht.

Außerdem hängt sie die YAML-Kette `haushalt` → `verfassungsklage_schulden` an die
bestehende DB-Option `haushalt/schulden` an.

`event_type` trägt wie bei den Story-Arcs (065/069) den Anzeigetyp (danger/warn/…);
das Frontend nimmt alle Events außerhalb der Spezialkategorien in den Zufalls-Pool.

Die Daten sind hier eingefroren und werden nicht zur Laufzeit aus dem YAML gelesen.

Revision ID: 070_random_events_nachseeden
Revises: 069_event_arc_ruestungsexport_sma272
"""

from __future__ import annotations

import json
from typing import Any, Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "070_random_events_nachseeden"
down_revision: Union[str, Sequence[str], None] = "069_event_arc_ruestungsexport_sma272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (id, event_type, min_complexity, repeatable, cooldown_months)
_EVENTS = [
    ("verfassungsgericht", "warn", 3, False, None),
    ("naturkatastrophe", "danger", 2, False, None),
    ("cyberangriff", "danger", 3, False, None),
    ("g7_krise", "warn", 3, False, None),
    ("whistleblower", "danger", 3, False, None),
    ("streikwelle", "warn", 1, True, 14),
    ("wohnungsnot", "info", 1, False, None),
    ("rechtsextremismus", "danger", 2, False, None),
    ("fachkraeftemangel", "warn", 1, True, 14),
    ("energiekrise", "danger", 1, True, 13),
    ("rentendebatte", "warn", 2, False, None),
    ("pandemie_vorbereitung", "warn", 2, False, None),
    ("infrastruktur_kollaps", "danger", 1, True, 12),
    ("migration_krise", "warn", 2, False, None),
    ("verfassungsklage_schulden", "danger", 1, False, None),
    ("wiederaufbau_debatte", "warn", 2, False, None),
    ("diplomatische_krise", "warn", 3, False, None),
    ("opposition_vorwurf", "danger", 2, False, None),
    ("gewerkschaft_eskalation", "danger", 1, False, None),
    ("bauernproteste", "danger", 1, False, None),
    ("pflegenotstand", "danger", 1, False, None),
    ("ki_vorfall", "danger", 3, False, None),
]

# (event_id, locale, type_label, title, quote, context, ticker)
_EVENTS_I18N = [
    (
        "verfassungsgericht",
        "de",
        "Verfassungsgericht",
        "Bundesverfassungsgericht kippt zentrale Regelung",
        "„Das Bundesverfassungsgericht erklärt ein Kerngesetz der Regierung für verfassungswidrig.“",
        "Die Richter in Karlsruhe sehen Grundrechte verletzt. Die Opposition triumphiert, die Koalition muss reagieren.",
        "Karlsruhe kippt Regierungsgesetz — Koalition unter Druck",
    ),
    (
        "verfassungsgericht",
        "en",
        "Constitutional Court",
        "Federal Constitutional Court strikes down key regulation",
        '"The Federal Constitutional Court declares a core government law unconstitutional."',
        "The judges in Karlsruhe see fundamental rights violated. The opposition triumphs, the coalition must respond.",
        "Karlsruhe strikes down government law — coalition under pressure",
    ),
    (
        "naturkatastrophe",
        "de",
        "Naturkatastrophe",
        "Jahrhunderthochwasser verwüstet Süddeutschland",
        "„Die schlimmste Flutkatastrophe seit Jahrzehnten fordert Dutzende Opfer und Milliardenschäden.“",
        "Ganze Ortschaften stehen unter Wasser. Der Katastrophenschutz ist am Limit. Die Bundesregierung muss schnell handeln.",
        "Hochwasser-Katastrophe: Bundesregierung aktiviert Krisenstab",
    ),
    (
        "naturkatastrophe",
        "en",
        "Natural disaster",
        "Century flood devastates southern Germany",
        '"The worst flood catastrophe in decades claims dozens of lives and causes billions in damage."',
        "Entire towns are underwater. Emergency services are at their limit. The federal government must act fast.",
        "Flood catastrophe: Federal government activates crisis team",
    ),
    (
        "cyberangriff",
        "de",
        "Cyberangriff",
        "Massive Cyberattacke legt Bundesministerien lahm",
        "„Ein koordinierter Hackerangriff hat zentrale IT-Systeme der Bundesverwaltung kompromittiert.“",
        "Geheimdienste vermuten einen staatlichen Akteur. Sensible Daten könnten abgeflossen sein. Die digitale Infrastruktur ist verwundbar.",
        "Cyberangriff auf Bundesregierung — IT-Systeme lahmgelegt",
    ),
    (
        "cyberangriff",
        "en",
        "Cyber attack",
        "Massive cyber attack paralyses federal ministries",
        '"A coordinated hacker attack has compromised central IT systems of the federal administration."',
        "Intelligence agencies suspect a state actor. Sensitive data may have been leaked.",
        "Cyber attack on federal government — IT systems paralysed",
    ),
    (
        "g7_krise",
        "de",
        "Internationale Krise",
        "G7-Gipfel unter dem Schatten globaler Spannungen",
        "„Internationale Konflikte überschatten den G7-Gipfel unter deutscher Präsidentschaft.“",
        "Die Weltöffentlichkeit blickt auf Berlin. Ein Scheitern des Gipfels wäre ein diplomatisches Desaster.",
        "G7-Gipfel in Berlin: Kanzler unter internationalem Druck",
    ),
    (
        "g7_krise",
        "en",
        "International crisis",
        "G7 summit overshadowed by global tensions",
        '"International conflicts overshadow the G7 summit under German presidency."',
        "The world is watching Berlin. A summit failure would be a diplomatic disaster.",
        "G7 summit in Berlin: Chancellor under international pressure",
    ),
    (
        "whistleblower",
        "de",
        "Whistleblower-Affäre",
        "Beamter enthüllt systematische Überwachung",
        "„Ein hochrangiger Beamter veröffentlicht brisante Dokumente über illegale Überwachungsprogramme.“",
        "Die Enthüllungen treffen den Verfassungsschutz ins Mark. Bürgerrechtler fordern Konsequenzen, Sicherheitsbehörden warnen vor Schwächung.",
        "Überwachungsskandal: Bürgerrechte vs. Sicherheit",
    ),
    (
        "whistleblower",
        "en",
        "Whistleblower affair",
        "Official reveals systematic surveillance",
        '"A senior official publishes explosive documents about illegal surveillance programmes."',
        "The revelations hit the domestic intelligence service hard. Civil rights advocates demand consequences.",
        "Surveillance scandal: Civil rights vs. security",
    ),
    (
        "streikwelle",
        "de",
        "Streikwelle",
        "Gewerkschaften rufen zum Generalstreik",
        "„Nahverkehr, Kitas, Krankenhäuser — eine Streikwelle lähmt das öffentliche Leben.“",
        "Die Tarifverhandlungen sind gescheitert. Gewerkschaften fordern zweistellige Lohnerhöhungen, Arbeitgeber warnen vor Standortgefährdung.",
        "Generalstreik lähmt Deutschland — Millionen betroffen",
    ),
    (
        "streikwelle",
        "en",
        "Strike wave",
        "Unions call for general strike",
        '"Public transport, daycare, hospitals — a strike wave paralyses public life."',
        "Wage negotiations have failed. Unions demand double-digit pay rises.",
        "General strike paralyses Germany — millions affected",
    ),
    (
        "wohnungsnot",
        "de",
        "Wohnungskrise",
        "Zehntausende protestieren gegen explodierende Mieten",
        "„In 50 Städten gehen Menschen auf die Straße — bezahlbarer Wohnraum ist die zentrale Forderung.“",
        "Die Mieten in Großstädten haben sich in 10 Jahren verdoppelt. Familien werden an den Stadtrand verdrängt, Sozialverbände schlagen Alarm.",
        "Wohnungsproteste in 50 Städten — Regierung unter Zugzwang",
    ),
    (
        "wohnungsnot",
        "en",
        "Housing crisis",
        "Tens of thousands protest against soaring rents",
        '"In 50 cities, people take to the streets — affordable housing is the central demand."',
        "Rents in major cities have doubled in 10 years. Families are being pushed to the outskirts.",
        "Housing protests in 50 cities — government under pressure",
    ),
    (
        "rechtsextremismus",
        "de",
        "Rechtsextremismus",
        "Rechtsextremer Anschlag erschüttert das Land",
        "„Ein rechtsmotivierter Anschlag fordert Opfer und löst eine Welle der Solidarität und Angst aus.“",
        "Die Tat reiht sich in eine Serie rechter Gewalt ein. Die Frage nach dem Versagen der Sicherheitsbehörden steht im Raum.",
        "Rechtsextremer Anschlag: Deutschland trauert und debattiert",
    ),
    (
        "rechtsextremismus",
        "en",
        "Right-wing extremism",
        "Right-wing extremist attack shakes the nation",
        '"A right-wing motivated attack claims victims and triggers a wave of solidarity and fear."',
        "The attack is part of a series of right-wing violence. The question of security agencies' failure looms.",
        "Right-wing extremist attack: Germany mourns and debates",
    ),
    (
        "fachkraeftemangel",
        "de",
        "Fachkräftemangel",
        "Fachkräftemangel bedroht Wirtschaftsstandort",
        "„800.000 offene Stellen können nicht besetzt werden — Unternehmen warnen vor Abwanderung.“",
        "Handwerk, IT, Pflege — überall fehlen Arbeitskräfte. Die Wirtschaftsverbände fordern eine Offensive.",
        "Fachkräftemangel auf Rekordhoch — Wirtschaft schlägt Alarm",
    ),
    (
        "fachkraeftemangel",
        "en",
        "Skills shortage",
        "Skills shortage threatens economic competitiveness",
        '"800,000 vacancies cannot be filled — companies warn of relocation."',
        "Trades, IT, care — workers are lacking everywhere. Business associations demand an offensive.",
        "Skills shortage at record high — business sounds alarm",
    ),
    (
        "energiekrise",
        "de",
        "Energiekrise",
        "Energiepreisschock trifft Industrie und Verbraucher",
        "„Gaspreise verdreifachen sich über Nacht — Industrie fährt Produktion herunter.“",
        "Internationale Lieferengpässe treiben die Preise. Verbraucher protestieren, Unternehmen drohen mit Verlagerung.",
        "Energiepreise explodieren — Wirtschaftsminister warnt vor Deindustrialisierung",
    ),
    (
        "energiekrise",
        "en",
        "Energy crisis",
        "Energy price shock hits industry and consumers",
        '"Gas prices triple overnight — industry scales back production."',
        "International supply bottlenecks drive prices. Consumers protest, companies threaten relocation.",
        "Energy prices explode — Economy Minister warns of deindustrialisation",
    ),
    (
        "rentendebatte",
        "de",
        "Rentenkrise",
        "Rentenversicherung meldet Milliardendefizit",
        "„Die Babyboomer gehen in Rente — das System steht vor dem Kollaps.“",
        "Der Rentenversicherungsbericht zeigt ein wachsendes Defizit. Jüngere Generationen fürchten um ihre Altersvorsorge.",
        "Rentenversicherung: Defizit wächst — Reformdebatte entbrennt",
    ),
    (
        "rentendebatte",
        "en",
        "Pension crisis",
        "Pension insurance reports billion-euro deficit",
        '"The baby boomers are retiring — the system faces collapse."',
        "The pension report shows a growing deficit. Younger generations fear for their retirement.",
        "Pension insurance: Deficit grows — reform debate ignites",
    ),
    (
        "pandemie_vorbereitung",
        "de",
        "Pandemie-Warnung",
        "WHO warnt vor neuem Virus mit Pandemiepotenzial",
        "„Eine neue Virusvariante breitet sich in Asien rasant aus — die WHO ruft zur Vorbereitung auf.“",
        "Deutschland hat aus der letzten Pandemie gelernt — oder doch nicht? Krankenhäuser melden Engpässe, Impfstoffreserven sind begrenzt.",
        "WHO-Warnung: Neue Pandemie möglich — Deutschland bereitet sich vor",
    ),
    (
        "pandemie_vorbereitung",
        "en",
        "Pandemic warning",
        "WHO warns of new virus with pandemic potential",
        '"A new virus variant is spreading rapidly in Asia — the WHO calls for preparation."',
        "Germany has learned from the last pandemic — or has it? Hospitals report bottlenecks.",
        "WHO warning: New pandemic possible — Germany prepares",
    ),
    (
        "infrastruktur_kollaps",
        "de",
        "Infrastruktur",
        "Brückensperrungen legen Verkehr lahm",
        "„Dutzende marode Autobahnbrücken müssen gesperrt werden — der Verkehr bricht zusammen.“",
        "Jahrzehntelang wurde die Infrastruktur vernachlässigt. LKW-Umleitungen kosten die Wirtschaft Milliarden.",
        "Infrastruktur-Krise: Marode Brücken lahmlegen Verkehr",
    ),
    (
        "infrastruktur_kollaps",
        "en",
        "Infrastructure",
        "Bridge closures paralyse traffic",
        '"Dozens of dilapidated motorway bridges must be closed — traffic collapses."',
        "Infrastructure has been neglected for decades. Truck detours cost the economy billions.",
        "Infrastructure crisis: Crumbling bridges paralyse traffic",
    ),
    (
        "migration_krise",
        "de",
        "Migrationskrise",
        "Flüchtlingszahlen steigen sprunghaft an",
        "„Kommunen melden Überlastung — die Aufnahmekapazitäten sind erschöpft.“",
        "Neue Konflikte treiben Hunderttausende nach Europa. Kommunalpolitiker fordern Hilfe vom Bund, die Stimmung in der Bevölkerung ist gespalten.",
        "Flüchtlingskrise: Kommunen am Limit — Bund unter Druck",
    ),
    (
        "migration_krise",
        "en",
        "Migration crisis",
        "Refugee numbers surge dramatically",
        '"Municipalities report overload — reception capacities are exhausted."',
        "New conflicts drive hundreds of thousands to Europe. Local politicians demand federal help.",
        "Refugee crisis: Municipalities at limit — federal government under pressure",
    ),
    (
        "verfassungsklage_schulden",
        "de",
        "Verfassungsklage",
        "Opposition klagt gegen Schuldenaufnahme",
        "„Die Opposition hat Klage beim Bundesverfassungsgericht eingereicht — Verstoß gegen die Schuldenbremse.“",
        "Die Klage hat Aussicht auf Erfolg. Ein Urteil könnte den Haushalt kippen und Neuwahlen erzwingen.",
        "Verfassungsklage gegen Schuldenpolitik — Regierung in Bedrängnis",
    ),
    (
        "verfassungsklage_schulden",
        "en",
        "Constitutional complaint",
        "Opposition sues over debt policy",
        '"The opposition has filed a complaint with the Federal Constitutional Court — violation of the debt brake."',
        "The complaint has prospects of success. A ruling could overturn the budget.",
        "Constitutional complaint against debt policy — government in trouble",
    ),
    (
        "wiederaufbau_debatte",
        "de",
        "Wiederaufbau",
        "Streit über Wiederaufbaukosten nach Flutkatastrophe",
        "„Wer zahlt die 30 Milliarden Euro Wiederaufbau? Bund und Länder streiten.“",
        "Die Flutopfer warten auf Hilfe, während Berlin und die Landeshauptsstädte über Zuständigkeiten debattieren.",
        "Wiederaufbau-Streit: Bund vs. Länder — Flutopfer warten",
    ),
    (
        "wiederaufbau_debatte",
        "en",
        "Reconstruction",
        "Dispute over reconstruction costs after flood",
        '"Who pays the 30 billion euros for reconstruction? Federation and states argue."',
        "Flood victims wait for help while Berlin and state capitals debate responsibilities.",
        "Reconstruction dispute: Federation vs. states — flood victims wait",
    ),
    (
        "diplomatische_krise",
        "de",
        "Diplomatische Krise",
        "Beschuldigter Staat reagiert mit Gegenmaßnahmen",
        "„Als Reaktion auf die öffentlichen Schuldzuweisungen verhängt der beschuldigte Staat Wirtschaftssanktionen.“",
        "Handelsbeziehungen sind gefährdet. Die Wirtschaft drängt auf Deeskalation, Sicherheitsexperten fordern Standhaftigkeit.",
        "Diplomatische Krise eskaliert — Wirtschaftssanktionen drohen",
    ),
    (
        "diplomatische_krise",
        "en",
        "Diplomatic crisis",
        "Accused state retaliates with countermeasures",
        '"In response to public accusations, the accused state imposes economic sanctions."',
        "Trade relations are at risk. Business urges de-escalation.",
        "Diplomatic crisis escalates — economic sanctions threaten",
    ),
    (
        "opposition_vorwurf",
        "de",
        "Opposition",
        "Opposition wirft Regierung Untätigkeit vor",
        "„Nach dem rechtsextremen Anschlag wirft die Opposition der Regierung fahrlässige Untätigkeit vor.“",
        "Ein Misstrauensantrag steht im Raum. Die Medien berichten intensiv über das Versagen der Sicherheitsbehörden.",
        "Opposition attackiert Regierung — Misstrauensantrag im Gespräch",
    ),
    (
        "opposition_vorwurf",
        "en",
        "Opposition",
        "Opposition accuses government of inaction",
        '"After the right-wing extremist attack, the opposition accuses the government of negligent inaction."',
        "A vote of no confidence is in the air. Media report intensively on security agency failures.",
        "Opposition attacks government — no-confidence vote discussed",
    ),
    (
        "gewerkschaft_eskalation",
        "de",
        "Streik-Eskalation",
        "Gewerkschaften weiten Streik aus",
        "„Nach dem Scheitern der Schlichtung rufen die Gewerkschaften zu unbefristeten Streiks auf.“",
        "Flughäfen, Häfen und Krankenhäuser sind betroffen. Die wirtschaftlichen Schäden gehen in die Milliarden.",
        "Unbefristeter Streik: Wirtschaft droht Stillstand",
    ),
    (
        "gewerkschaft_eskalation",
        "en",
        "Strike escalation",
        "Unions extend strike indefinitely",
        '"After mediation fails, unions call for indefinite strikes."',
        "Airports, ports and hospitals are affected. Economic damage runs into billions.",
        "Indefinite strike: Economy faces standstill",
    ),
    (
        "bauernproteste",
        "de",
        "Agrarkrise",
        "Bauern blockieren Autobahnen und Ministerien",
        "„Tausende Traktoren rollen auf Berlin zu — die Stimmung auf dem Land ist am Siedepunkt.“",
        "Bauernverbände protestieren gegen den geplanten Abbau von Agrardiesel-Subventionen und steigende Auflagen. Wirtschaftsministerin Maier warnt vor Versorgungsengpässen, Innenminister Braun fordert klare Kante.",
        "Bauernprotest: Traktoren blockieren Hauptstadt — Regierung unter Druck",
    ),
    (
        "bauernproteste",
        "en",
        "Agricultural crisis",
        "Farmers block motorways and ministries",
        "Thousands of tractors are heading for Berlin — the mood in rural areas is at boiling point.",
        "Farmers' associations are protesting against the planned reduction of agricultural diesel subsidies and rising regulatory burdens. Economics Minister Maier warns of supply shortages; Interior Minister Braun demands firm action.",
        "Farmers' protest: tractors block capital — government under pressure",
    ),
    (
        "pflegenotstand",
        "de",
        "Gesundheitskrise",
        "Kliniken schlagen Alarm — Pflegenotstand offiziell",
        "„Wir können die Versorgung nicht mehr garantieren“, warnt die Deutsche Krankenhausgesellschaft.",
        "Hunderttausende Pflegestellen sind unbesetzt. Gesundheitsminister Neumann fordert sofortiges Handeln — die Krankenkassen sperren sich gegen höhere Beiträge.",
        "Pflegenotstand: Krankenhäuser warnen vor Versorgungskollaps",
    ),
    (
        "pflegenotstand",
        "en",
        "Health crisis",
        "Hospitals sound the alarm — care emergency declared",
        "We can no longer guarantee care, warns the German Hospital Association.",
        "Hundreds of thousands of care positions are unfilled. Health Minister Neumann demands immediate action — health insurers resist higher contributions.",
        "Care emergency: hospitals warn of care system collapse",
    ),
    (
        "ki_vorfall",
        "de",
        "Digitaler Angriff",
        "KI-Deepfake-Angriff auf Bundesbehörde aufgedeckt",
        "„Ein KI-generiertes Video des Bundesinnenministers verbreitete sich unkontrolliert in sozialen Netzwerken.“",
        "Ein staatlicher Akteur nutzte generative KI für gezielte Desinformation. Das BSI ist überfordert — die EU-Kommission fordert nationale Notfallregulierung, bevor der EU AI Act greift.",
        "KI-Deepfake-Skandal: Bundesbehörde Ziel staatlicher Desinformation",
    ),
    (
        "ki_vorfall",
        "en",
        "Digital attack",
        "AI deepfake attack on federal agency uncovered",
        "An AI-generated video of the Federal Interior Minister spread uncontrollably on social networks.",
        "A state actor used generative AI for targeted disinformation. The BSI is overwhelmed — the EU Commission demands national emergency regulation before the EU AI Act takes effect.",
        "AI deepfake scandal: federal agency targeted by state disinformation",
    ),
]

# (event_id, choice_key, choice_type, cost_pk, al, hh, gi, zf, char_mood,
#  followup_event_id, followup_delay, unlocks_laws)
_CHOICES = [
    (
        "verfassungsgericht",
        "urteil_respektieren",
        "safe",
        0,
        0,
        0,
        0,
        -3,
        {"jm": 1},
        None,
        None,
        None,
    ),
    (
        "verfassungsgericht",
        "gesetzesnovelle_einbringen",
        "primary",
        15,
        0,
        -0.2,
        0,
        1,
        {},
        None,
        None,
        ["verfassungsreform"],
    ),
    (
        "verfassungsgericht",
        "verfassungsaenderung_pruefen",
        "danger",
        20,
        0,
        0,
        0,
        -1,
        {"jm": -2},
        None,
        None,
        ["verfassungsreform"],
    ),
    (
        "naturkatastrophe",
        "soforthilfe_paket",
        "primary",
        5,
        0,
        -0.5,
        0,
        5,
        {"fm": -1},
        "wiederaufbau_debatte",
        2,
        ["katastrophenschutz"],
    ),
    (
        "naturkatastrophe",
        "bundeswehr_einsatz_koordinieren",
        "safe",
        10,
        0,
        0,
        0,
        3,
        {"im": 1},
        None,
        None,
        ["katastrophenschutz"],
    ),
    (
        "naturkatastrophe",
        "laendersache_abwarten",
        "danger",
        0,
        0,
        0,
        0,
        -6,
        {"im": -1},
        None,
        None,
        None,
    ),
    (
        "cyberangriff",
        "krisenstab_it_offensive",
        "primary",
        15,
        0,
        -0.3,
        0,
        2,
        {"im": 1},
        None,
        None,
        ["cybersicherheit"],
    ),
    (
        "cyberangriff",
        "geheimdienste_ermitteln_lassen",
        "safe",
        5,
        0,
        0,
        0,
        -2,
        {"jm": -1},
        None,
        None,
        ["cybersicherheit"],
    ),
    (
        "cyberangriff",
        "diplomatische_eskalation",
        "danger",
        10,
        0,
        0,
        0,
        -1,
        {},
        "diplomatische_krise",
        3,
        None,
    ),
    (
        "g7_krise",
        "vermittlerrolle_einnehmen",
        "primary",
        10,
        0,
        -0.1,
        0,
        3,
        {},
        None,
        None,
        None,
    ),
    (
        "g7_krise",
        "buendnistreue_demonstrieren",
        "safe",
        5,
        0,
        0,
        0,
        1,
        {"im": 1},
        None,
        None,
        None,
    ),
    (
        "g7_krise",
        "deutsche_interessen_priorisieren",
        "danger",
        0,
        0,
        0,
        0,
        -2,
        {"um": -1},
        None,
        None,
        None,
    ),
    (
        "whistleblower",
        "untersuchungsausschuss",
        "primary",
        10,
        0,
        0,
        0,
        2,
        {"jm": 1, "im": -2},
        None,
        None,
        ["whistleblowerschutz"],
    ),
    (
        "whistleblower",
        "whistleblower_schuetzen",
        "safe",
        5,
        0,
        0,
        0,
        1,
        {"jm": 2, "im": -1},
        None,
        None,
        ["whistleblowerschutz"],
    ),
    (
        "whistleblower",
        "sicherheitsinteressen_betonen",
        "danger",
        0,
        0,
        0,
        0,
        -4,
        {"im": 1, "jm": -1},
        None,
        None,
        None,
    ),
    (
        "streikwelle",
        "schlichtung_anbieten",
        "primary",
        10,
        -0.2,
        0,
        0,
        2,
        {"wm": 1},
        None,
        None,
        ["tarifbindung"],
    ),
    (
        "streikwelle",
        "arbeitgeberseite_unterstuetzen",
        "danger",
        5,
        -0.4,
        0,
        0.5,
        -3,
        {},
        "gewerkschaft_eskalation",
        2,
        None,
    ),
    (
        "streikwelle",
        "gesetzlichen_rahmen_staerken",
        "safe",
        15,
        0,
        0,
        0,
        1,
        {},
        None,
        None,
        ["tarifbindung"],
    ),
    (
        "wohnungsnot",
        "mietpreisbremse_verschaerfen",
        "primary",
        5,
        0,
        -0.1,
        -0.5,
        4,
        {},
        None,
        None,
        ["mietrecht"],
    ),
    (
        "wohnungsnot",
        "sozialen_wohnungsbau_foerdern",
        "safe",
        10,
        -0.2,
        -0.4,
        0,
        3,
        {},
        None,
        None,
        ["mietrecht"],
    ),
    (
        "wohnungsnot",
        "marktloesung_betonen",
        "danger",
        0,
        0,
        0,
        0.3,
        -4,
        {},
        None,
        None,
        None,
    ),
    (
        "rechtsextremismus",
        "aktionsplan_gegen_rechts",
        "primary",
        15,
        0,
        0,
        0,
        3,
        {"jm": 1, "im": 1},
        None,
        None,
        ["demokratiefoerderung"],
    ),
    (
        "rechtsextremismus",
        "sicherheitsbehoerden_staerken",
        "safe",
        10,
        0,
        -0.2,
        0,
        1,
        {"im": 2},
        None,
        None,
        ["demokratiefoerderung"],
    ),
    (
        "rechtsextremismus",
        "differenzierte_analyse",
        "danger",
        0,
        0,
        0,
        0,
        -5,
        {},
        "opposition_vorwurf",
        1,
        None,
    ),
    (
        "fachkraeftemangel",
        "einwanderungsoffensive",
        "primary",
        10,
        -0.4,
        0,
        0,
        2,
        {"wm": 1, "im": -1},
        None,
        None,
        ["fachkraefte"],
    ),
    (
        "fachkraeftemangel",
        "ausbildungsinitiative",
        "safe",
        10,
        -0.1,
        0,
        0,
        1,
        {"wm": 1},
        None,
        None,
        ["fachkraefte"],
    ),
    (
        "fachkraeftemangel",
        "markt_regelt",
        "danger",
        0,
        0.3,
        0,
        0,
        -3,
        {"wm": -1},
        None,
        None,
        None,
    ),
    (
        "energiekrise",
        "preisbremse_einfuehren",
        "primary",
        10,
        0,
        -0.5,
        -0.3,
        4,
        {"fm": -1, "wm": 1},
        None,
        None,
        None,
    ),
    (
        "energiekrise",
        "industrie_subventionen",
        "safe",
        15,
        -0.3,
        -0.4,
        0,
        2,
        {"wm": 1},
        None,
        None,
        None,
    ),
    (
        "energiekrise",
        "marktpreise_akzeptieren",
        "danger",
        0,
        0.4,
        0,
        0.2,
        -5,
        {"fm": 1},
        None,
        None,
        None,
    ),
    (
        "rentendebatte",
        "rentenalter_anheben",
        "primary",
        10,
        0,
        0.3,
        0,
        -4,
        {"fm": 1},
        None,
        None,
        ["rentenreform"],
    ),
    (
        "rentendebatte",
        "beitraege_erhoehen",
        "safe",
        5,
        0.1,
        0.2,
        0,
        -2,
        {},
        None,
        None,
        ["rentenreform"],
    ),
    (
        "rentendebatte",
        "kapitaldeckung_einfuehren",
        "danger",
        15,
        0,
        -0.2,
        0,
        -1,
        {"fm": -1},
        None,
        None,
        ["rentenreform"],
    ),
    (
        "pandemie_vorbereitung",
        "vorsorgepaket_schnueren",
        "primary",
        15,
        0,
        -0.4,
        0,
        3,
        {},
        None,
        None,
        ["pandemieschutz"],
    ),
    (
        "pandemie_vorbereitung",
        "who_kooperation_verstaerken",
        "safe",
        5,
        0,
        0,
        0,
        1,
        {},
        None,
        None,
        ["pandemieschutz"],
    ),
    (
        "pandemie_vorbereitung",
        "abwarten_und_beobachten",
        "danger",
        0,
        0,
        0,
        0,
        -3,
        {},
        None,
        None,
        None,
    ),
    (
        "infrastruktur_kollaps",
        "notfallprogramm_infrastruktur",
        "primary",
        10,
        -0.2,
        -0.5,
        0,
        3,
        {"wm": 1, "fm": -1},
        None,
        None,
        ["schienen"],
    ),
    (
        "infrastruktur_kollaps",
        "kommunen_entlasten",
        "safe",
        5,
        0,
        -0.2,
        0,
        1,
        {},
        None,
        None,
        ["schienen"],
    ),
    (
        "infrastruktur_kollaps",
        "priorisieren_und_planen",
        "danger",
        0,
        0,
        0,
        0,
        -3,
        {"wm": -1},
        None,
        None,
        None,
    ),
    (
        "migration_krise",
        "humanitaere_aufnahme",
        "primary",
        10,
        0,
        -0.3,
        0,
        -2,
        {"jm": 1, "im": -1},
        None,
        None,
        None,
    ),
    (
        "migration_krise",
        "eu_verteilung_einfordern",
        "safe",
        5,
        0,
        0,
        0,
        1,
        {},
        None,
        None,
        None,
    ),
    (
        "migration_krise",
        "grenzkontrollen_verstaerken",
        "danger",
        5,
        0,
        0,
        -0.2,
        2,
        {"im": 2, "jm": -2},
        None,
        None,
        None,
    ),
    (
        "verfassungsklage_schulden",
        "nachtragshaushalt_vorlegen",
        "primary",
        15,
        0,
        0.2,
        0,
        -2,
        {"fm": 1},
        None,
        None,
        None,
    ),
    (
        "verfassungsklage_schulden",
        "notlage_erklaeren",
        "safe",
        5,
        0,
        0,
        0,
        -3,
        {"jm": -1},
        None,
        None,
        None,
    ),
    (
        "verfassungsklage_schulden",
        "klage_aussitzen",
        "danger",
        0,
        0,
        0,
        0,
        -5,
        {"jm": -2},
        None,
        None,
        None,
    ),
    (
        "wiederaufbau_debatte",
        "solidaritaetszuschlag_erheben",
        "primary",
        5,
        0,
        0.3,
        0,
        -3,
        {"fm": 1},
        None,
        None,
        None,
    ),
    (
        "wiederaufbau_debatte",
        "sondervermoegen_einrichten",
        "safe",
        10,
        0,
        -0.3,
        0,
        2,
        {},
        None,
        None,
        None,
    ),
    (
        "wiederaufbau_debatte",
        "versicherungspflicht_einfuehren",
        "safe",
        5,
        0,
        0,
        0,
        -1,
        {},
        None,
        None,
        None,
    ),
    (
        "diplomatische_krise",
        "deeskalation",
        "primary",
        10,
        0,
        0,
        -0.2,
        1,
        {},
        None,
        None,
        None,
    ),
    (
        "diplomatische_krise",
        "gegensanktionen",
        "danger",
        5,
        0,
        -0.2,
        -0.5,
        -2,
        {"im": 1},
        None,
        None,
        None,
    ),
    (
        "diplomatische_krise",
        "eu_solidaritaet_einfordern",
        "safe",
        5,
        0,
        0,
        0,
        0,
        {},
        None,
        None,
        None,
    ),
    (
        "opposition_vorwurf",
        "sofort_massnahmen_verkuenden",
        "primary",
        15,
        0,
        -0.2,
        0,
        2,
        {"im": 1},
        None,
        None,
        ["demokratiefoerderung"],
    ),
    (
        "opposition_vorwurf",
        "vertrauensfrage_stellen",
        "danger",
        0,
        0,
        0,
        0,
        -4,
        {},
        None,
        None,
        None,
    ),
    (
        "opposition_vorwurf",
        "debatte_im_parlament",
        "safe",
        5,
        0,
        0,
        0,
        -1,
        {"jm": 1},
        None,
        None,
        None,
    ),
    (
        "gewerkschaft_eskalation",
        "tarifeinigung_erzwingen",
        "primary",
        15,
        -0.3,
        -0.1,
        0,
        1,
        {},
        None,
        None,
        None,
    ),
    (
        "gewerkschaft_eskalation",
        "kompromiss_anbieten",
        "safe",
        10,
        0,
        -0.3,
        0,
        2,
        {"wm": 1},
        None,
        None,
        None,
    ),
    (
        "gewerkschaft_eskalation",
        "durchhalten",
        "danger",
        0,
        0.3,
        0,
        -0.3,
        -4,
        {"wm": -1},
        None,
        None,
        None,
    ),
    (
        "bauernproteste",
        "sofortprogramm_auflegen",
        "primary",
        15,
        -0.1,
        -0.3,
        0,
        4,
        {"wm": 1, "im": 1},
        None,
        None,
        ["bauernentlastung"],
    ),
    (
        "bauernproteste",
        "dialog_anbieten",
        "safe",
        5,
        0,
        0,
        -0.1,
        1,
        {"wm": 1},
        None,
        None,
        ["bauernentlastung"],
    ),
    (
        "bauernproteste",
        "polizei_durchgreifen_lassen",
        "danger",
        10,
        0,
        0,
        0.3,
        -5,
        {"im": 1, "wm": -1},
        None,
        None,
        None,
    ),
    (
        "pflegenotstand",
        "sofortprogramm_pflege",
        "primary",
        10,
        0,
        -0.4,
        0,
        5,
        {"gm": 2},
        None,
        None,
        ["pflegepersonal"],
    ),
    (
        "pflegenotstand",
        "experten_kommission_einsetzen",
        "safe",
        5,
        0,
        0,
        0,
        1,
        {"gm": 1, "fm": 1},
        None,
        None,
        ["pflegepersonal"],
    ),
    (
        "pflegenotstand",
        "krankenkassen_in_die",
        "safe",
        0,
        0,
        0.2,
        0.3,
        -2,
        {"gm": 1, "fm": 1, "wm": -1},
        None,
        None,
        None,
    ),
    (
        "ki_vorfall",
        "ki_einsatzstopp_in",
        "primary",
        10,
        0,
        -0.1,
        0,
        3,
        {"im": 1, "jm": 1, "wm": -1},
        None,
        None,
        ["ki_regulierung"],
    ),
    (
        "ki_vorfall",
        "regulierung_beschleunigen",
        "safe",
        15,
        0,
        0,
        -0.2,
        2,
        {"jm": 1, "wm": 1},
        None,
        None,
        ["ki_regulierung"],
    ),
    (
        "ki_vorfall",
        "eu_koordination_suchen",
        "danger",
        5,
        0,
        0,
        0,
        -1,
        {"im": -1},
        None,
        None,
        None,
    ),
]

# (event_id, choice_key, locale, label, desc, log_msg)
_CHOICES_I18N = [
    (
        "verfassungsgericht",
        "urteil_respektieren",
        "de",
        "Urteil respektieren",
        "Rechtsstaatlich korrekt, politischer Schaden",
        "Urteil akzeptiert. Vertrauen in Rechtsstaat gestärkt.",
    ),
    (
        "verfassungsgericht",
        "urteil_respektieren",
        "en",
        "Respect ruling",
        "Rule of law, political damage",
        "Ruling accepted. Trust in rule of law strengthened.",
    ),
    (
        "verfassungsgericht",
        "gesetzesnovelle_einbringen",
        "de",
        "Gesetzesnovelle einbringen",
        "Nachbesserung kostet PK und Haushalt",
        "Gesetzesnovelle in Arbeit. Verfassungskonform nachgebessert.",
    ),
    (
        "verfassungsgericht",
        "gesetzesnovelle_einbringen",
        "en",
        "Introduce amendment",
        "Revision costs PK and budget",
        "Legislative amendment in progress. Constitutionally corrected.",
    ),
    (
        "verfassungsgericht",
        "verfassungsaenderung_pruefen",
        "de",
        "Verfassungsänderung prüfen",
        "Riskant — Grundgesetz anfassen spaltet",
        "Grundgesetzänderung angekündigt. Juristen und Opposition alarmiert.",
    ),
    (
        "verfassungsgericht",
        "verfassungsaenderung_pruefen",
        "en",
        "Consider constitutional change",
        "Risky — touching Basic Law divides",
        "Constitutional amendment announced. Jurists and opposition alarmed.",
    ),
    (
        "naturkatastrophe",
        "soforthilfe_paket",
        "de",
        "Soforthilfe-Paket",
        "Schnelle Hilfe, belastet Haushalt",
        "Soforthilfe-Paket beschlossen. Schnelle Hilfe für Betroffene.",
    ),
    (
        "naturkatastrophe",
        "soforthilfe_paket",
        "en",
        "Emergency aid package",
        "Fast help, burdens budget",
        "Emergency aid package passed. Fast help for those affected.",
    ),
    (
        "naturkatastrophe",
        "bundeswehr_einsatz_koordinieren",
        "de",
        "Bundeswehr-Einsatz koordinieren",
        "Effektiv, aber begrenzte Mittel",
        "Bundeswehr im Hilfseinsatz. Bevölkerung dankbar.",
    ),
    (
        "naturkatastrophe",
        "bundeswehr_einsatz_koordinieren",
        "en",
        "Coordinate army deployment",
        "Effective but limited resources",
        "Army in relief deployment. Population grateful.",
    ),
    (
        "naturkatastrophe",
        "laendersache_abwarten",
        "de",
        "Ländersache — abwarten",
        "Föderalismus betonen, riskiert Kritik",
        "Bund verweist auf Länderzuständigkeit. Massive Kritik folgt.",
    ),
    (
        "naturkatastrophe",
        "laendersache_abwarten",
        "en",
        "State matter — wait",
        "Emphasise federalism, risks criticism",
        "Federation points to state responsibility. Massive criticism follows.",
    ),
    (
        "cyberangriff",
        "krisenstab_it_offensive",
        "de",
        "Krisenstab & IT-Offensive",
        "Sofort handeln, investieren",
        "IT-Krisenstab eingerichtet. Cybersicherheit wird Chefsache.",
    ),
    (
        "cyberangriff",
        "krisenstab_it_offensive",
        "en",
        "Crisis team & IT offensive",
        "Act immediately, invest",
        "IT crisis team established. Cybersecurity becomes top priority.",
    ),
    (
        "cyberangriff",
        "geheimdienste_ermitteln_lassen",
        "de",
        "Geheimdienste ermitteln lassen",
        "Leise, aber langsam",
        "Ermittlungen eingeleitet. Öffentlichkeit erfährt wenig.",
    ),
    (
        "cyberangriff",
        "geheimdienste_ermitteln_lassen",
        "en",
        "Let intelligence investigate",
        "Quiet but slow",
        "Investigation initiated. Public learns little.",
    ),
    (
        "cyberangriff",
        "diplomatische_eskalation",
        "de",
        "Diplomatische Eskalation",
        "Öffentlich beschuldigen, Risiko einer Krise",
        "Diplomatische Konfrontation. Internationale Spannungen steigen.",
    ),
    (
        "cyberangriff",
        "diplomatische_eskalation",
        "en",
        "Diplomatic escalation",
        "Publicly accuse, risk of crisis",
        "Diplomatic confrontation. International tensions rise.",
    ),
    (
        "g7_krise",
        "vermittlerrolle_einnehmen",
        "de",
        "Vermittlerrolle einnehmen",
        "Diplomatisch geschickt, kostet PK",
        "Deutschland als Vermittler. Internationales Ansehen steigt.",
    ),
    (
        "g7_krise",
        "vermittlerrolle_einnehmen",
        "en",
        "Take mediator role",
        "Diplomatically skilled, costs PK",
        "Germany as mediator. International reputation rises.",
    ),
    (
        "g7_krise",
        "buendnistreue_demonstrieren",
        "de",
        "Bündnistreue demonstrieren",
        "Sichere Wahl, begrenzte Wirkung",
        "Bündnistreue demonstriert. Partnerstaat zufrieden.",
    ),
    (
        "g7_krise",
        "buendnistreue_demonstrieren",
        "en",
        "Demonstrate alliance loyalty",
        "Safe choice, limited impact",
        "Alliance loyalty demonstrated. Partner state satisfied.",
    ),
    (
        "g7_krise",
        "deutsche_interessen_priorisieren",
        "de",
        "Deutsche Interessen priorisieren",
        "Populär im Inland, isoliert international",
        "Nationale Interessen betont. Internationale Kritik wächst.",
    ),
    (
        "g7_krise",
        "deutsche_interessen_priorisieren",
        "en",
        "Prioritise German interests",
        "Popular domestically, isolated internationally",
        "National interests emphasised. International criticism grows.",
    ),
    (
        "whistleblower",
        "untersuchungsausschuss",
        "de",
        "Untersuchungsausschuss",
        "Transparenz, kostet politisch",
        "Untersuchungsausschuss eingesetzt. Aufklärung beginnt.",
    ),
    (
        "whistleblower",
        "untersuchungsausschuss",
        "en",
        "Investigation committee",
        "Transparency, political cost",
        "Investigation committee established. Inquiry begins.",
    ),
    (
        "whistleblower",
        "whistleblower_schuetzen",
        "de",
        "Whistleblower schützen",
        "Mutig, spaltet Koalition",
        "Whistleblower unter Schutz gestellt. Verfassungsschutz empört.",
    ),
    (
        "whistleblower",
        "whistleblower_schuetzen",
        "en",
        "Protect whistleblower",
        "Brave, divides coalition",
        "Whistleblower placed under protection. Intelligence service outraged.",
    ),
    (
        "whistleblower",
        "sicherheitsinteressen_betonen",
        "de",
        "Sicherheitsinteressen betonen",
        "Behörden stärken, Kritik ignorieren",
        "Sicherheit über Transparenz gestellt. Bürgerrechtler protestieren.",
    ),
    (
        "whistleblower",
        "sicherheitsinteressen_betonen",
        "en",
        "Emphasise security interests",
        "Strengthen agencies, ignore criticism",
        "Security over transparency. Civil rights advocates protest.",
    ),
    (
        "streikwelle",
        "schlichtung_anbieten",
        "de",
        "Schlichtung anbieten",
        "Kompromiss suchen, kostet PK",
        "Schlichtungsverfahren eingeleitet. Sozialpartner am Verhandlungstisch.",
    ),
    (
        "streikwelle",
        "schlichtung_anbieten",
        "en",
        "Offer mediation",
        "Seek compromise, costs PK",
        "Mediation proceedings initiated. Social partners at the table.",
    ),
    (
        "streikwelle",
        "arbeitgeberseite_unterstuetzen",
        "de",
        "Arbeitgeberseite unterstützen",
        "Wirtschaftsnah, provoziert Eskalation",
        "Arbeitgeberposition gestärkt. Gewerkschaften drohen mit Eskalation.",
    ),
    (
        "streikwelle",
        "arbeitgeberseite_unterstuetzen",
        "en",
        "Support employer side",
        "Business-friendly, provokes escalation",
        "Employer position strengthened. Unions threaten escalation.",
    ),
    (
        "streikwelle",
        "gesetzlichen_rahmen_staerken",
        "de",
        "Gesetzlichen Rahmen stärken",
        "Langfristig, kurzfristig wirkungslos",
        "Tarifrecht-Reform angekündigt. Langfristige Lösung in Aussicht.",
    ),
    (
        "streikwelle",
        "gesetzlichen_rahmen_staerken",
        "en",
        "Strengthen legal framework",
        "Long-term, short-term ineffective",
        "Labour law reform announced. Long-term solution in sight.",
    ),
    (
        "wohnungsnot",
        "mietpreisbremse_verschaerfen",
        "de",
        "Mietpreisbremse verschärfen",
        "Populär, belastet Investoren",
        "Mietpreisbremse verschärft. Mieterverbände zufrieden, Investoren verärgert.",
    ),
    (
        "wohnungsnot",
        "mietpreisbremse_verschaerfen",
        "en",
        "Tighten rent cap",
        "Popular, burdens investors",
        "Rent cap tightened. Tenant associations satisfied, investors angered.",
    ),
    (
        "wohnungsnot",
        "sozialen_wohnungsbau_foerdern",
        "de",
        "Sozialen Wohnungsbau fördern",
        "Langfristig wirksam, teuer",
        "Sozialwohnungsprogramm aufgelegt. Effekte erst in Jahren spürbar.",
    ),
    (
        "wohnungsnot",
        "sozialen_wohnungsbau_foerdern",
        "en",
        "Promote social housing",
        "Effective long-term, expensive",
        "Social housing programme launched. Effects visible in years.",
    ),
    (
        "wohnungsnot",
        "marktloesung_betonen",
        "de",
        "Marktlösung betonen",
        "Wirtschaftsfreundlich, unpopulär",
        "Markt soll es richten. Proteste verschärfen sich.",
    ),
    (
        "wohnungsnot",
        "marktloesung_betonen",
        "en",
        "Emphasise market solutions",
        "Business-friendly, unpopular",
        "Market should fix it. Protests intensify.",
    ),
    (
        "rechtsextremismus",
        "aktionsplan_gegen_rechts",
        "de",
        "Aktionsplan gegen Rechts",
        "Umfassend, zeigt Entschlossenheit",
        "Aktionsplan gegen Rechtsextremismus beschlossen.",
    ),
    (
        "rechtsextremismus",
        "aktionsplan_gegen_rechts",
        "en",
        "Action plan against the far right",
        "Comprehensive, shows determination",
        "Action plan against right-wing extremism passed.",
    ),
    (
        "rechtsextremismus",
        "sicherheitsbehoerden_staerken",
        "de",
        "Sicherheitsbehörden stärken",
        "Mehr Personal und Mittel",
        "Verfassungsschutz und Polizei werden aufgestockt.",
    ),
    (
        "rechtsextremismus",
        "sicherheitsbehoerden_staerken",
        "en",
        "Strengthen security agencies",
        "More personnel and resources",
        "Intelligence and police forces expanded.",
    ),
    (
        "rechtsextremismus",
        "differenzierte_analyse",
        "de",
        "Differenzierte Analyse",
        "Abwägend, wirkt zögerlich",
        "Abwartende Haltung. Opposition wirft Untätigkeit vor.",
    ),
    (
        "rechtsextremismus",
        "differenzierte_analyse",
        "en",
        "Differentiated analysis",
        "Considered, appears hesitant",
        "Wait-and-see stance. Opposition accuses of inaction.",
    ),
    (
        "fachkraeftemangel",
        "einwanderungsoffensive",
        "de",
        "Einwanderungsoffensive",
        "Schnell wirksam, gesellschaftlich umstritten",
        "Fachkräfteeinwanderung erleichtert. Wirtschaft erleichtert.",
    ),
    (
        "fachkraeftemangel",
        "einwanderungsoffensive",
        "en",
        "Immigration offensive",
        "Quickly effective, socially controversial",
        "Skilled immigration facilitated. Business relieved.",
    ),
    (
        "fachkraeftemangel",
        "ausbildungsinitiative",
        "de",
        "Ausbildungsinitiative",
        "Langfristig richtig, langsam",
        "Ausbildungsoffensive gestartet. Effekte in Jahren spürbar.",
    ),
    (
        "fachkraeftemangel",
        "ausbildungsinitiative",
        "en",
        "Training initiative",
        "Right long-term, slow",
        "Training offensive launched. Effects visible in years.",
    ),
    (
        "fachkraeftemangel",
        "markt_regelt",
        "de",
        "Markt regelt",
        "Keine Kosten, kein Effekt",
        "Abwartende Haltung. Fachkräftemangel verschärft sich.",
    ),
    (
        "fachkraeftemangel",
        "markt_regelt",
        "en",
        "Let the market sort it out",
        "No costs, no effect",
        "Wait-and-see stance. Skills shortage worsens.",
    ),
    (
        "energiekrise",
        "preisbremse_einfuehren",
        "de",
        "Preisbremse einführen",
        "Sofortige Entlastung, teuer",
        "Energiepreisbremse greift. Haushalt stark belastet.",
    ),
    (
        "energiekrise",
        "preisbremse_einfuehren",
        "en",
        "Introduce price brake",
        "Immediate relief, expensive",
        "Energy price brake takes effect. Budget heavily burdened.",
    ),
    (
        "energiekrise",
        "industrie_subventionen",
        "de",
        "Industrie-Subventionen",
        "Rettet Arbeitsplätze, umstritten",
        "Industriesubventionen beschlossen. Arbeitsplätze gesichert.",
    ),
    (
        "energiekrise",
        "industrie_subventionen",
        "en",
        "Industry subsidies",
        "Saves jobs, controversial",
        "Industry subsidies passed. Jobs secured.",
    ),
    (
        "energiekrise",
        "marktpreise_akzeptieren",
        "de",
        "Marktpreise akzeptieren",
        "Sparwillig, sozial hart",
        "Marktpreise durchgesetzt. Soziale Härten folgen.",
    ),
    (
        "energiekrise",
        "marktpreise_akzeptieren",
        "en",
        "Accept market prices",
        "Thrifty, socially harsh",
        "Market prices enforced. Social hardship follows.",
    ),
    (
        "rentendebatte",
        "rentenalter_anheben",
        "de",
        "Rentenalter anheben",
        "Unpopulär, finanziell notwendig",
        "Rentenalter auf 68 angehoben. Massive Proteste der Gewerkschaften.",
    ),
    (
        "rentendebatte",
        "rentenalter_anheben",
        "en",
        "Raise retirement age",
        "Unpopular, financially necessary",
        "Retirement age raised to 68. Massive union protests.",
    ),
    (
        "rentendebatte",
        "beitraege_erhoehen",
        "de",
        "Beiträge erhöhen",
        "Verteilbar, senkt Nettolöhne",
        "Rentenbeiträge steigen. Nettolöhne sinken leicht.",
    ),
    (
        "rentendebatte",
        "beitraege_erhoehen",
        "en",
        "Raise contributions",
        "Distributable, lowers net wages",
        "Pension contributions rise. Net wages drop slightly.",
    ),
    (
        "rentendebatte",
        "kapitaldeckung_einfuehren",
        "de",
        "Kapitaldeckung einführen",
        "Modern, riskant bei Krisen",
        "Aktienrente eingeführt. Konservative skeptisch.",
    ),
    (
        "rentendebatte",
        "kapitaldeckung_einfuehren",
        "en",
        "Introduce capital funding",
        "Modern, risky in crises",
        "Stock-based pension introduced. Conservatives sceptical.",
    ),
    (
        "pandemie_vorbereitung",
        "vorsorgepaket_schnueren",
        "de",
        "Vorsorgepaket schnüren",
        "Impfstoffe, Masken, Krankenhaus-Kapazitäten",
        "Pandemie-Vorsorgepaket beschlossen. Bevölkerung fühlt sich geschützt.",
    ),
    (
        "pandemie_vorbereitung",
        "vorsorgepaket_schnueren",
        "en",
        "Prepare prevention package",
        "Vaccines, masks, hospital capacity",
        "Pandemic prevention package passed. Population feels protected.",
    ),
    (
        "pandemie_vorbereitung",
        "who_kooperation_verstaerken",
        "de",
        "WHO-Kooperation verstärken",
        "International, aber langsam",
        "Internationale Kooperation ausgebaut. Abwarten in Deutschland.",
    ),
    (
        "pandemie_vorbereitung",
        "who_kooperation_verstaerken",
        "en",
        "Strengthen WHO cooperation",
        "International but slow",
        "International cooperation expanded. Wait-and-see in Germany.",
    ),
    (
        "pandemie_vorbereitung",
        "abwarten_und_beobachten",
        "de",
        "Abwarten und beobachten",
        "Keine Kosten, aber riskant",
        "Abwartende Haltung. Kritiker warnen vor Fahrlässigkeit.",
    ),
    (
        "pandemie_vorbereitung",
        "abwarten_und_beobachten",
        "en",
        "Wait and observe",
        "No costs but risky",
        "Wait-and-see stance. Critics warn of negligence.",
    ),
    (
        "infrastruktur_kollaps",
        "notfallprogramm_infrastruktur",
        "de",
        "Notfallprogramm Infrastruktur",
        "Sofort investieren, teuer",
        "Infrastruktur-Notfallprogramm aufgelegt. Milliarden für Brücken und Straßen.",
    ),
    (
        "infrastruktur_kollaps",
        "notfallprogramm_infrastruktur",
        "en",
        "Emergency infrastructure programme",
        "Invest immediately, expensive",
        "Infrastructure emergency programme launched. Billions for bridges and roads.",
    ),
    (
        "infrastruktur_kollaps",
        "kommunen_entlasten",
        "de",
        "Kommunen entlasten",
        "Föderale Lösung, langsamer",
        "Kommunale Infrastrukturhilfen beschlossen.",
    ),
    (
        "infrastruktur_kollaps",
        "kommunen_entlasten",
        "en",
        "Support municipalities",
        "Federal solution, slower",
        "Municipal infrastructure aid passed.",
    ),
    (
        "infrastruktur_kollaps",
        "priorisieren_und_planen",
        "de",
        "Priorisieren und planen",
        "Sparsam, aber Kritik an Untätigkeit",
        "Masterplan vorgelegt. Kritiker fordern sofortiges Handeln.",
    ),
    (
        "infrastruktur_kollaps",
        "priorisieren_und_planen",
        "en",
        "Prioritise and plan",
        "Thrifty, but criticism of inaction",
        "Master plan presented. Critics demand immediate action.",
    ),
    (
        "migration_krise",
        "humanitaere_aufnahme",
        "de",
        "Humanitäre Aufnahme",
        "Menschlich, spaltet Gesellschaft",
        "Humanitäre Aufnahme organisiert. Gesellschaft gespalten.",
    ),
    (
        "migration_krise",
        "humanitaere_aufnahme",
        "en",
        "Humanitarian reception",
        "Humane, divides society",
        "Humanitarian reception organised. Society divided.",
    ),
    (
        "migration_krise",
        "eu_verteilung_einfordern",
        "de",
        "EU-Verteilung einfordern",
        "Diplomatisch, dauert lang",
        "EU-Verteilungsmechanismus gefordert. Brüssel reagiert zögerlich.",
    ),
    (
        "migration_krise",
        "eu_verteilung_einfordern",
        "en",
        "Demand EU distribution",
        "Diplomatic, takes time",
        "EU distribution mechanism demanded. Brussels reacts slowly.",
    ),
    (
        "migration_krise",
        "grenzkontrollen_verstaerken",
        "de",
        "Grenzkontrollen verstärken",
        "Populär, EU-rechtlich umstritten",
        "Grenzkontrollen verschärft. EU-Kommission prüft Verfahren.",
    ),
    (
        "migration_krise",
        "grenzkontrollen_verstaerken",
        "en",
        "Strengthen border controls",
        "Popular, EU-legally controversial",
        "Border controls tightened. EU Commission examines proceedings.",
    ),
    (
        "verfassungsklage_schulden",
        "nachtragshaushalt_vorlegen",
        "de",
        "Nachtragshaushalt vorlegen",
        "Verfassungskonform nachbessern",
        "Nachtragshaushalt vorgelegt. Schuldenbremse eingehalten.",
    ),
    (
        "verfassungsklage_schulden",
        "nachtragshaushalt_vorlegen",
        "en",
        "Present supplementary budget",
        "Constitutionally correct revision",
        "Supplementary budget presented. Debt brake complied with.",
    ),
    (
        "verfassungsklage_schulden",
        "notlage_erklaeren",
        "de",
        "Notlage erklären",
        "Ausnahmeregel nutzen",
        "Notlage erklärt. Juristen zweifeln an Begründung.",
    ),
    (
        "verfassungsklage_schulden",
        "notlage_erklaeren",
        "en",
        "Declare emergency",
        "Use exception rule",
        "Emergency declared. Jurists doubt justification.",
    ),
    (
        "verfassungsklage_schulden",
        "klage_aussitzen",
        "de",
        "Klage aussitzen",
        "Riskant, aber billig",
        "Klage ignoriert. Verfassungsgericht verärgert.",
    ),
    (
        "verfassungsklage_schulden",
        "klage_aussitzen",
        "en",
        "Sit out complaint",
        "Risky but cheap",
        "Complaint ignored. Constitutional Court angered.",
    ),
    (
        "wiederaufbau_debatte",
        "solidaritaetszuschlag_erheben",
        "de",
        "Solidaritätszuschlag erheben",
        "Faire Verteilung, unpopulär",
        "Solidaritätszuschlag für Wiederaufbau. Steuerzahler protestieren.",
    ),
    (
        "wiederaufbau_debatte",
        "solidaritaetszuschlag_erheben",
        "en",
        "Levy solidarity surcharge",
        "Fair distribution, unpopular",
        "Solidarity surcharge for reconstruction. Taxpayers protest.",
    ),
    (
        "wiederaufbau_debatte",
        "sondervermoegen_einrichten",
        "de",
        "Sondervermögen einrichten",
        "Schnell, belastet Zukunft",
        "Sondervermögen für Wiederaufbau beschlossen.",
    ),
    (
        "wiederaufbau_debatte",
        "sondervermoegen_einrichten",
        "en",
        "Establish special fund",
        "Fast, burdens the future",
        "Special fund for reconstruction passed.",
    ),
    (
        "wiederaufbau_debatte",
        "versicherungspflicht_einfuehren",
        "de",
        "Versicherungspflicht einführen",
        "Marktwirtschaftlich, langfristig",
        "Pflichtversicherung gegen Elementarschäden eingeführt.",
    ),
    (
        "wiederaufbau_debatte",
        "versicherungspflicht_einfuehren",
        "en",
        "Introduce insurance mandate",
        "Market-based, long-term",
        "Mandatory insurance against natural disasters introduced.",
    ),
    (
        "diplomatische_krise",
        "deeskalation",
        "de",
        "Deeskalation",
        "Gesicht wahren, Handel retten",
        "Diplomatische Kanäle wieder geöffnet. Krise entschärft.",
    ),
    (
        "diplomatische_krise",
        "deeskalation",
        "en",
        "De-escalation",
        "Save face, rescue trade",
        "Diplomatic channels reopened. Crisis defused.",
    ),
    (
        "diplomatische_krise",
        "gegensanktionen",
        "de",
        "Gegensanktionen",
        "Standhaft, wirtschaftlich teuer",
        "Gegensanktionen verhängt. Wirtschaft leidet.",
    ),
    (
        "diplomatische_krise",
        "gegensanktionen",
        "en",
        "Counter-sanctions",
        "Steadfast, economically costly",
        "Counter-sanctions imposed. Economy suffers.",
    ),
    (
        "diplomatische_krise",
        "eu_solidaritaet_einfordern",
        "de",
        "EU-Solidarität einfordern",
        "Multilateral, braucht Zeit",
        "EU-Partner um Solidarität gebeten. Reaktionen gemischt.",
    ),
    (
        "diplomatische_krise",
        "eu_solidaritaet_einfordern",
        "en",
        "Demand EU solidarity",
        "Multilateral, takes time",
        "EU partners asked for solidarity. Mixed reactions.",
    ),
    (
        "opposition_vorwurf",
        "sofort_massnahmen_verkuenden",
        "de",
        "Sofort-Maßnahmen verkünden",
        "Entschlossen reagieren",
        "Sofortmaßnahmen gegen Rechtsextremismus verkündet.",
    ),
    (
        "opposition_vorwurf",
        "sofort_massnahmen_verkuenden",
        "en",
        "Announce immediate measures",
        "Respond decisively",
        "Immediate measures against right-wing extremism announced.",
    ),
    (
        "opposition_vorwurf",
        "vertrauensfrage_stellen",
        "de",
        "Vertrauensfrage stellen",
        "Alles auf eine Karte",
        "Vertrauensfrage gestellt. Hochriskantes Manöver.",
    ),
    (
        "opposition_vorwurf",
        "vertrauensfrage_stellen",
        "en",
        "Call vote of confidence",
        "All-or-nothing",
        "Vote of confidence called. High-risk manoeuvre.",
    ),
    (
        "opposition_vorwurf",
        "debatte_im_parlament",
        "de",
        "Debatte im Parlament führen",
        "Demokratisch, aber langsam",
        "Parlamentsdebatte über innere Sicherheit. Sachlicher Ton.",
    ),
    (
        "opposition_vorwurf",
        "debatte_im_parlament",
        "en",
        "Lead parliamentary debate",
        "Democratic but slow",
        "Parliamentary debate on internal security. Measured tone.",
    ),
    (
        "gewerkschaft_eskalation",
        "tarifeinigung_erzwingen",
        "de",
        "Tarifeinigung erzwingen",
        "Staatliche Schlichtung, kostet Vertrauen",
        "Zwangsschlichtung angeordnet. Gewerkschaften empört, Streik beendet.",
    ),
    (
        "gewerkschaft_eskalation",
        "tarifeinigung_erzwingen",
        "en",
        "Force wage agreement",
        "State mediation, costs trust",
        "Compulsory arbitration ordered. Unions outraged, strike ended.",
    ),
    (
        "gewerkschaft_eskalation",
        "kompromiss_anbieten",
        "de",
        "Kompromiss anbieten",
        "Teurer Kompromiss",
        "Kompromiss gefunden. Löhne steigen, Haushalt belastet.",
    ),
    (
        "gewerkschaft_eskalation",
        "kompromiss_anbieten",
        "en",
        "Offer compromise",
        "Expensive compromise",
        "Compromise found. Wages rise, budget burdened.",
    ),
    (
        "gewerkschaft_eskalation",
        "durchhalten",
        "de",
        "Durchhalten",
        "Auf Zeit spielen, wirtschaftlicher Schaden",
        "Regierung hält Kurs. Wirtschaftliche Schäden wachsen.",
    ),
    (
        "gewerkschaft_eskalation",
        "durchhalten",
        "en",
        "Hold firm",
        "Play for time, economic damage",
        "Government holds course. Economic damage grows.",
    ),
    (
        "bauernproteste",
        "sofortprogramm_auflegen",
        "de",
        "Sofortprogramm auflegen",
        "Agrardiesel-Kompensation und Bürokratieabbau — teuer, aber deeskalierend",
        "Sofortprogramm für Landwirte beschlossen. Proteste nehmen ab, Haushalt belastet.",
    ),
    (
        "bauernproteste",
        "sofortprogramm_auflegen",
        "en",
        "Launch emergency programme",
        "Agricultural diesel compensation and deregulation — costly but de-escalating",
        "Emergency programme for farmers passed. Protests ease, budget burdened.",
    ),
    (
        "bauernproteste",
        "dialog_anbieten",
        "de",
        "Dialog anbieten",
        "Runden Tisch einberufen — gewinnt Zeit, löst nichts sofort",
        "Agrar-Runder Tisch einberufen. Bauern skeptisch, Proteste dauern an.",
    ),
    (
        "bauernproteste",
        "dialog_anbieten",
        "en",
        "Offer dialogue",
        "Convene a round table — buys time, solves nothing immediately",
        "Agricultural round table convened. Farmers sceptical, protests continue.",
    ),
    (
        "bauernproteste",
        "polizei_durchgreifen_lassen",
        "de",
        "Polizei durchgreifen lassen",
        "Räumung der Blockaden — politisch riskant",
        "Polizeieinsatz gegen Blockaden. Stimmung auf dem Land kippt dauerhaft.",
    ),
    (
        "bauernproteste",
        "polizei_durchgreifen_lassen",
        "en",
        "Order police to clear blockades",
        "Clearing blockades — politically risky",
        "Police action against blockades. Rural sentiment shifts permanently.",
    ),
    (
        "pflegenotstand",
        "sofortprogramm_pflege",
        "de",
        "Sofortprogramm Pflege",
        "Pflegepersonalgesetz beschleunigt einbringen — kostet viel",
        "Pflegesofortprogramm beschlossen. Neumann erleichtert, Haushalt belastet.",
    ),
    (
        "pflegenotstand",
        "sofortprogramm_pflege",
        "en",
        "Launch care emergency programme",
        "Fast-track nursing staff act — expensive",
        "Care emergency programme passed. Neumann relieved, budget burdened.",
    ),
    (
        "pflegenotstand",
        "experten_kommission_einsetzen",
        "de",
        "Experten-Kommission einsetzen",
        "Gewinnt Zeit, senkt Druck — aber keine Sofortwirkung",
        "Expertenkommission Pflege eingesetzt. Bericht in 6 Monaten erwartet.",
    ),
    (
        "pflegenotstand",
        "experten_kommission_einsetzen",
        "en",
        "Appoint expert commission",
        "Buys time, reduces pressure — but no immediate effect",
        "Expert commission on care appointed. Report expected in 6 months.",
    ),
    (
        "pflegenotstand",
        "krankenkassen_in_die",
        "de",
        "Krankenkassen in die Pflicht nehmen",
        "Beitragserhöhung — unpopulär, aber wirksam",
        "Krankenkassen müssen Pflegefinanzierung anheben. Kritik aus der Wirtschaft.",
    ),
    (
        "pflegenotstand",
        "krankenkassen_in_die",
        "en",
        "Require health insurers to act",
        "Contribution increase — unpopular but effective",
        "Health insurers must increase care funding. Business criticism follows.",
    ),
    (
        "ki_vorfall",
        "ki_einsatzstopp_in",
        "de",
        "KI-Einsatzstopp in Behörden",
        "Sicherheitspause — hemmt Innovation, schützt sofort",
        "KI-Einsatzstopp für Bundesbehörden verhängt. BSI prüft alle Systeme.",
    ),
    (
        "ki_vorfall",
        "ki_einsatzstopp_in",
        "en",
        "Suspend AI in government agencies",
        "Security pause — hampers innovation, protects immediately",
        "AI use suspended in federal agencies. BSI reviewing all systems.",
    ),
    (
        "ki_vorfall",
        "regulierung_beschleunigen",
        "de",
        "Regulierung beschleunigen",
        "KI-Governance-Gesetz sofort einbringen",
        "KI-Regulierungsinitiative gestartet. Branche reagiert gemischt.",
    ),
    (
        "ki_vorfall",
        "regulierung_beschleunigen",
        "en",
        "Accelerate regulation",
        "Fast-track AI governance act",
        "AI regulation initiative launched. Industry reaction mixed.",
    ),
    (
        "ki_vorfall",
        "eu_koordination_suchen",
        "de",
        "EU-Koordination suchen",
        "Auf europäische Lösung warten — Zeitverlust",
        "EU-Koordination angefragt. Bis zur Antwort bleibt das Risiko bestehen.",
    ),
    (
        "ki_vorfall",
        "eu_koordination_suchen",
        "en",
        "Seek EU coordination",
        "Wait for a European solution — loses time",
        "EU coordination requested. Risk remains until response arrives.",
    ),
]

# (event_id, choice_key, followup_event_id, followup_delay) — Ketten an bestehende Optionen
_FOLLOWUP_UPDATES = [("haushalt", "schulden", "verfassungsklage_schulden", 2)]


def upgrade() -> None:
    conn = op.get_bind()
    for eid, event_type, min_complexity, repeatable, cooldown_months in _EVENTS:
        conn.execute(
            sa.text(
                """
                INSERT INTO events (
                    id, event_type, min_complexity, repeatable, cooldown_months
                )
                VALUES (:id, :event_type, :min_complexity, :repeatable, :cooldown)
                """
            ),
            {
                "id": eid,
                "event_type": event_type,
                "min_complexity": min_complexity,
                "repeatable": repeatable,
                "cooldown": cooldown_months,
            },
        )
    for eid, locale, type_label, title, quote, context, ticker in _EVENTS_I18N:
        conn.execute(
            sa.text(
                """
                INSERT INTO events_i18n (
                    event_id, locale, type_label, title, quote, context, ticker
                )
                VALUES (:eid, :locale, :type_label, :title, :quote, :context, :ticker)
                """
            ),
            {
                "eid": eid,
                "locale": locale,
                "type_label": type_label,
                "title": title,
                "quote": quote,
                "context": context,
                "ticker": ticker,
            },
        )
    choice_ids: dict[tuple[str, str], Any] = {}
    for (
        eid,
        choice_key,
        choice_type,
        cost_pk,
        al,
        hh,
        gi,
        zf,
        char_mood,
        followup_event_id,
        followup_delay,
        unlocks_laws,
    ) in _CHOICES:
        result = conn.execute(
            sa.text(
                """
                INSERT INTO event_choices (
                    event_id, choice_key, choice_type, cost_pk,
                    effekt_al, effekt_hh, effekt_gi, effekt_zf,
                    char_mood, followup_event_id, followup_delay, unlocks_laws
                )
                VALUES (
                    :eid, :key, :type, :cost_pk,
                    :al, :hh, :gi, :zf,
                    CAST(:char_mood AS jsonb), :followup_event_id, :followup_delay,
                    :unlocks_laws
                )
                RETURNING id
                """
            ),
            {
                "eid": eid,
                "key": choice_key,
                "type": choice_type,
                "cost_pk": cost_pk,
                "al": al,
                "hh": hh,
                "gi": gi,
                "zf": zf,
                "char_mood": json.dumps(char_mood),
                "followup_event_id": followup_event_id,
                "followup_delay": followup_delay,
                "unlocks_laws": unlocks_laws,
            },
        )
        choice_ids[(eid, choice_key)] = result.scalar_one()
    for eid, choice_key, locale, label, desc, log_msg in _CHOICES_I18N:
        conn.execute(
            sa.text(
                """
                INSERT INTO event_choices_i18n (choice_id, locale, label, "desc", log_msg)
                VALUES (:choice_id, :locale, :label, :desc, :log_msg)
                """
            ),
            {
                "choice_id": choice_ids[(eid, choice_key)],
                "locale": locale,
                "label": label,
                "desc": desc,
                "log_msg": log_msg,
            },
        )
    for eid, choice_key, followup_event_id, followup_delay in _FOLLOWUP_UPDATES:
        conn.execute(
            sa.text(
                """
                UPDATE event_choices
                SET followup_event_id = :followup, followup_delay = :delay
                WHERE event_id = :eid AND choice_key = :key
                """
            ),
            {
                "eid": eid,
                "key": choice_key,
                "followup": followup_event_id,
                "delay": followup_delay,
            },
        )


def downgrade() -> None:
    conn = op.get_bind()
    for eid, choice_key, _followup, _delay in _FOLLOWUP_UPDATES:
        conn.execute(
            sa.text(
                """
                UPDATE event_choices
                SET followup_event_id = NULL, followup_delay = NULL
                WHERE event_id = :eid AND choice_key = :key
                """
            ),
            {"eid": eid, "key": choice_key},
        )
    event_ids = [eid for eid, *_ in _EVENTS]
    conn.execute(
        sa.text(
            "DELETE FROM event_choices_i18n WHERE choice_id IN "
            "(SELECT id FROM event_choices WHERE event_id = ANY(:eids))"
        ),
        {"eids": event_ids},
    )
    conn.execute(
        sa.text("DELETE FROM event_choices WHERE event_id = ANY(:eids)"),
        {"eids": event_ids},
    )
    conn.execute(
        sa.text("DELETE FROM events_i18n WHERE event_id = ANY(:eids)"),
        {"eids": event_ids},
    )
    conn.execute(
        sa.text("DELETE FROM events WHERE id = ANY(:eids)"),
        {"eids": event_ids},
    )
